In [2]:
from pathlib import Path
import sys

# Project root
PROJECT_ROOT = Path.cwd().parent

# Add project root to Python path
sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/apple/dev/EvoFinGraph

In [3]:
from src.graph.builder import TemporalGraphBuilder

In [4]:
builder = TemporalGraphBuilder()

2026-06-30 21:14:39,585 | INFO | Loading processed dataset...
2026-06-30 21:14:52,185 | INFO | Dataset loaded successfully.

In [5]:
G = builder.build_snapshot(20)

2026-06-30 21:14:52,196 | INFO | Building graph for timestep 20
2026-06-30 21:14:52,375 | INFO | Graph built successfully | Nodes: 900 | Edges: 613

In [6]:
print(type(G))

<class 'networkx.classes.digraph.DiGraph'>

In [7]:
print("Nodes :", G.number_of_nodes())
print("Edges :", G.number_of_edges())

Nodes : 900
Edges : 613

In [8]:
node = list(G.nodes())[0]

node

np.float64(209556175.0)

In [9]:
G.nodes[node]

{'label': 0,
 'timestep': 20,
 'features': array([-0.17203984,  0.93356565, -0.09138345,  4.15516838, -0.04387455,
         3.57693649,  0.24271234, -0.16364521, -0.16868463, -0.04839205,
        -0.1659324 ,  0.63094145,  2.41400531, -0.0429553 , -0.01328161,
        -0.05251233, -0.17052874, -0.17259332, -0.17514801,  0.88705787,
         0.88455653, -0.13973186, -0.04025147, -0.05126814, -0.15316482,
         0.59769528,  1.65113477, -0.13973366, -0.04023953, -0.05126763,
        -0.15316452,  0.5977823 ,  1.65113037, -0.02466883, -0.03127097,
        -0.02304367, -0.02621462, -1.14757025, -0.18360513, -0.22720599,
         0.8351729 ,  0.59142966, -0.21488731,  0.90466207,  2.1080308 ,
        -0.22719348,  0.32920799,  0.44292184, -0.225085  ,  0.91885592,
         2.08257608, -0.39192924,  2.40298603,  2.12224136,  0.6660601 ,
         0.84799233,  0.81788927, -0.03909367, -0.07282871, -0.05658159,
        -0.06116722,  0.92347298,  0.92301071, -0.03908894, -0.07280981,
        -0.05656919, -0.06115659,  0.9235163 ,  0.92311013, -0.01703168,
        -0.03002624, -0.01764012, -0.0150709 , -0.14076322, -0.14033462,
        -0.09517862,  0.71885865,  0.76082871,  0.72829512,  1.13352668,
         1.1359467 , -0.05876867,  0.29202552,  0.31443482,  0.30540381,
         1.12558961,  1.12803803,  0.41329071,  1.62739033,  1.88146141,
         1.64156161,  1.13552275,  1.1352787 , -0.17108508, -0.060026  ,
        -0.04130366, -0.18379374,  0.60904536, -0.14552183, -0.2314754 ,
        -0.24666057, -0.08182634, -0.24207342, -0.55396519, -0.541569  ,
        -0.16654995,  0.94093884,  1.20710636,  0.46334167, -1.38429949,
        -1.58534275, -1.09633569,  0.7874347 ,  1.69570063, -0.73481159,
         1.18115195,  0.88703971, -0.1164246 ,  1.41154075,  0.55808475,
        -0.09237596,  0.90020955,  1.42694436, -0.09314473,  2.6918927 ,
         2.04274236,  1.68742212, -1.83431063, -2.02845019, -0.12319812,
         2.93007336,  3.78547148,  3.38308468, -1.1596488 , -1.16012886,
        -0.22623713, -0.33735736, -0.27605535, -0.27651023, -0.97573751,
        -0.97523656, -0.04789898, -0.14125018, -0.08295904, -0.09606633,
        -1.01596337, -1.01623043, -0.96890287, -0.89842627,  0.15320933,
        -1.07188529,  1.4881129 ,  1.48793248,  0.1382544 ,  2.16266737,
         2.69605185,  2.33826667, -0.97907377, -0.97855605, -0.09888874,
        -0.08749016, -0.08467423, -0.14059708,  1.51969962,  1.52139948])}

In [10]:
list(G.edges())[:10]

[(np.float64(37574467.0), np.int64(209970507)),
 (np.float64(37574467.0), np.int64(209972191)),
 (np.float64(37574467.0), np.int64(209865519)),
 (np.float64(37574467.0), np.int64(209970517)),
 (np.float64(37574467.0), np.int64(209836059)),
 (np.float64(73339227.0), np.int64(209837677)),
 (np.float64(73339227.0), np.int64(2272609)),
 (np.float64(210644361.0), np.int64(25642291)),
 (np.float64(209952987.0), np.int64(209952974)),
 (np.float64(209952974.0), np.int64(210638488))]

GRAPH STATS

In [11]:
from src.graph.statistics import GraphStatistics

stats = GraphStatistics.summarize(G)

stats

{'timestep': 20,
 'nodes': 900,
 'edges': 613,
 'average_degree': 1.3622222222222222,
 'density': 0.0007576319367198121,
 'weakly_connected_components': 313,
 'isolated_nodes': 264}

In [15]:
"""test manager"""
from src.config import DEV_SNAPSHOTS
from src.graph.manager import TemporalGraphManager

manager = TemporalGraphManager()

manager.build_all(DEV_SNAPSHOTS)

2026-06-30 21:22:39,309 | INFO | Loading processed dataset...
2026-06-30 21:22:51,407 | INFO | Dataset loaded successfully.
2026-06-30 21:22:51,409 | INFO | Building temporal graphs...
2026-06-30 21:22:51,409 | INFO | Building graph for timestep 20
2026-06-30 21:22:51,593 | INFO | Graph built successfully | Nodes: 900 | Edges: 613
2026-06-30 21:22:51,594 | INFO | Snapshot 20 validated.
2026-06-30 21:22:51,645 | INFO | Detected 327 communities.
2026-06-30 21:22:51,647 | INFO | Building graph for timestep 21
2026-06-30 21:22:51,803 | INFO | Graph built successfully | Nodes: 641 | Edges: 518
2026-06-30 21:22:51,804 | INFO | Snapshot 21 validated.
2026-06-30 21:22:51,835 | INFO | Detected 238 communities.
2026-06-30 21:22:51,837 | INFO | Building graph for timestep 22
2026-06-30 21:22:52,195 | INFO | Graph built successfully | Nodes: 1763 | Edges: 1537
2026-06-30 21:22:52,196 | INFO | Snapshot 22 validated.
2026-06-30 21:22:52,296 | INFO | Detected 536 communities.
2026-06-30 21:22:52,299 | INFO | Building graph for timestep 23
2026-06-30 21:22:52,549 | INFO | Graph built successfully | Nodes: 1187 | Edges: 1046
2026-06-30 21:22:52,550 | INFO | Snapshot 23 validated.
2026-06-30 21:22:52,615 | INFO | Detected 210 communities.
2026-06-30 21:22:52,618 | INFO | Building graph for timestep 24
2026-06-30 21:22:52,856 | INFO | Graph built successfully | Nodes: 1126 | Edges: 961
2026-06-30 21:22:52,857 | INFO | Snapshot 24 validated.
2026-06-30 21:22:52,931 | INFO | Detected 254 communities.
2026-06-30 21:22:52,933 | INFO | Built 5 graphs.

In [16]:
manager.graphs.keys()

dict_keys([20, 21, 22, 23, 24])

In [17]:
manager.save_graphs()

manager.save_statistics()

In [18]:
import pandas as pd

stats = pd.read_csv(
    "../data/snapshots/graph_statistics.csv"
)

stats

,timestep,nodes,edges,average_degree,density,weakly_connected_components,isolated_nodes
0,20,900,613,1.362222,0.000758,313,264
1,21,641,518,1.616225,0.001263,224,197
2,22,1763,1537,1.743619,0.000495,469,408
3,23,1187,1046,1.762426,0.000743,186,135
4,24,1126,961,1.706927,0.000759,236,178

Table 2 for paper

BUILD ALL 49 GRPAHS

In [19]:
from src.config import ALL_SNAPSHOTS

In [20]:
manager = TemporalGraphManager()

manager.build_all(
    ALL_SNAPSHOTS
)

2026-06-30 21:24:56,588 | INFO | Loading processed dataset...
2026-06-30 21:25:09,255 | INFO | Dataset loaded successfully.
2026-06-30 21:25:09,258 | INFO | Building temporal graphs...
2026-06-30 21:25:09,259 | INFO | Building graph for timestep 1
2026-06-30 21:25:09,702 | INFO | Graph built successfully | Nodes: 2147 | Edges: 1924
2026-06-30 21:25:09,703 | INFO | Snapshot 1 validated.
2026-06-30 21:25:09,820 | INFO | Detected 437 communities.
2026-06-30 21:25:09,824 | INFO | Building graph for timestep 2
2026-06-30 21:25:10,058 | INFO | Graph built successfully | Nodes: 1117 | Edges: 858
2026-06-30 21:25:10,058 | INFO | Snapshot 2 validated.
2026-06-30 21:25:10,120 | INFO | Detected 322 communities.
2026-06-30 21:25:10,123 | INFO | Building graph for timestep 3
2026-06-30 21:25:10,398 | INFO | Graph built successfully | Nodes: 1279 | Edges: 727
2026-06-30 21:25:10,399 | INFO | Snapshot 3 validated.
2026-06-30 21:25:10,466 | INFO | Detected 558 communities.
2026-06-30 21:25:10,468 | INFO | Building graph for timestep 4
2026-06-30 21:25:10,766 | INFO | Graph built successfully | Nodes: 1440 | Edges: 1169
2026-06-30 21:25:10,767 | INFO | Snapshot 4 validated.
2026-06-30 21:25:10,843 | INFO | Detected 305 communities.
2026-06-30 21:25:10,846 | INFO | Building graph for timestep 5
2026-06-30 21:25:11,284 | INFO | Graph built successfully | Nodes: 1882 | Edges: 1491
2026-06-30 21:25:11,285 | INFO | Snapshot 5 validated.
2026-06-30 21:25:11,389 | INFO | Detected 468 communities.
2026-06-30 21:25:11,393 | INFO | Building graph for timestep 6
2026-06-30 21:25:11,503 | INFO | Graph built successfully | Nodes: 485 | Edges: 209
2026-06-30 21:25:11,504 | INFO | Snapshot 6 validated.
2026-06-30 21:25:11,526 | INFO | Detected 282 communities.
2026-06-30 21:25:11,528 | INFO | Building graph for timestep 7
2026-06-30 21:25:11,799 | INFO | Graph built successfully | Nodes: 1203 | Edges: 858
2026-06-30 21:25:11,800 | INFO | Snapshot 7 validated.
2026-06-30 21:25:11,875 | INFO | Detected 409 communities.
2026-06-30 21:25:11,877 | INFO | Building graph for timestep 8
2026-06-30 21:25:12,130 | INFO | Graph built successfully | Nodes: 1165 | Edges: 1044
2026-06-30 21:25:12,131 | INFO | Snapshot 8 validated.
2026-06-30 21:25:12,188 | INFO | Detected 228 communities.
2026-06-30 21:25:12,190 | INFO | Building graph for timestep 9
2026-06-30 21:25:12,356 | INFO | Graph built successfully | Nodes: 778 | Edges: 484
2026-06-30 21:25:12,357 | INFO | Snapshot 9 validated.
2026-06-30 21:25:12,398 | INFO | Detected 312 communities.
2026-06-30 21:25:12,400 | INFO | Building graph for timestep 10
2026-06-30 21:25:12,603 | INFO | Graph built successfully | Nodes: 972 | Edges: 538
2026-06-30 21:25:12,604 | INFO | Snapshot 10 validated.
2026-06-30 21:25:12,649 | INFO | Detected 458 communities.
2026-06-30 21:25:12,652 | INFO | Building graph for timestep 11
2026-06-30 21:25:12,824 | INFO | Graph built successfully | Nodes: 696 | Edges: 477
2026-06-30 21:25:12,826 | INFO | Snapshot 11 validated.
2026-06-30 21:25:12,879 | INFO | Detected 282 communities.
2026-06-30 21:25:12,881 | INFO | Building graph for timestep 12
2026-06-30 21:25:13,004 | INFO | Graph built successfully | Nodes: 506 | Edges: 446
2026-06-30 21:25:13,005 | INFO | Snapshot 12 validated.
2026-06-30 21:25:13,032 | INFO | Detected 102 communities.
2026-06-30 21:25:13,033 | INFO | Building graph for timestep 13
2026-06-30 21:25:13,206 | INFO | Graph built successfully | Nodes: 809 | Edges: 564
2026-06-30 21:25:13,207 | INFO | Snapshot 13 validated.
2026-06-30 21:25:13,253 | INFO | Detected 285 communities.
2026-06-30 21:25:13,255 | INFO | Building graph for timestep 14
2026-06-30 21:25:13,352 | INFO | Graph built successfully | Nodes: 417 | Edges: 350
2026-06-30 21:25:13,353 | INFO | Snapshot 14 validated.
2026-06-30 21:25:13,375 | INFO | Detected 91 communities.
2026-06-30 21:25:13,376 | INFO | Building graph for timestep 15
2026-06-30 21:25:13,518 | INFO | Graph built successfully | Nodes: 618 | Edges: 446
2026-06-30 21:25:13,519 | INFO | Snapshot 15 validated.
2026-06-30 21:25:13,552 | INFO | Detected 231 communities.
2026-06-30 21:25:13,553 | INFO | Building graph for timestep 16
2026-06-30 21:25:13,675 | INFO | Graph built successfully | Nodes: 530 | Edges: 334
2026-06-30 21:25:13,675 | INFO | Snapshot 16 validated.
2026-06-30 21:25:13,698 | INFO | Detected 224 communities.
2026-06-30 21:25:13,700 | INFO | Building graph for timestep 17
2026-06-30 21:25:13,880 | INFO | Graph built successfully | Nodes: 811 | Edges: 673
2026-06-30 21:25:13,881 | INFO | Snapshot 17 validated.
2026-06-30 21:25:13,924 | INFO | Detected 198 communities.
2026-06-30 21:25:13,926 | INFO | Building graph for timestep 18
2026-06-30 21:25:14,027 | INFO | Graph built successfully | Nodes: 389 | Edges: 275
2026-06-30 21:25:14,027 | INFO | Snapshot 18 validated.
2026-06-30 21:25:14,043 | INFO | Detected 126 communities.
2026-06-30 21:25:14,044 | INFO | Building graph for timestep 19
2026-06-30 21:25:14,215 | INFO | Graph built successfully | Nodes: 745 | Edges: 585
2026-06-30 21:25:14,216 | INFO | Snapshot 19 validated.
2026-06-30 21:25:14,261 | INFO | Detected 198 communities.
2026-06-30 21:25:14,263 | INFO | Building graph for timestep 20
2026-06-30 21:25:14,454 | INFO | Graph built successfully | Nodes: 900 | Edges: 613
2026-06-30 21:25:14,454 | INFO | Snapshot 20 validated.
2026-06-30 21:25:14,508 | INFO | Detected 327 communities.
2026-06-30 21:25:14,510 | INFO | Building graph for timestep 21
2026-06-30 21:25:14,659 | INFO | Graph built successfully | Nodes: 641 | Edges: 518
2026-06-30 21:25:14,660 | INFO | Snapshot 21 validated.
2026-06-30 21:25:14,692 | INFO | Detected 238 communities.
2026-06-30 21:25:14,693 | INFO | Building graph for timestep 22
2026-06-30 21:25:15,070 | INFO | Graph built successfully | Nodes: 1763 | Edges: 1537
2026-06-30 21:25:15,071 | INFO | Snapshot 22 validated.
2026-06-30 21:25:15,177 | INFO | Detected 536 communities.
2026-06-30 21:25:15,180 | INFO | Building graph for timestep 23
2026-06-30 21:25:15,430 | INFO | Graph built successfully | Nodes: 1187 | Edges: 1046
2026-06-30 21:25:15,431 | INFO | Snapshot 23 validated.
2026-06-30 21:25:15,495 | INFO | Detected 210 communities.
2026-06-30 21:25:15,497 | INFO | Building graph for timestep 24
2026-06-30 21:25:15,731 | INFO | Graph built successfully | Nodes: 1126 | Edges: 961
2026-06-30 21:25:15,732 | INFO | Snapshot 24 validated.
2026-06-30 21:25:15,801 | INFO | Detected 254 communities.
2026-06-30 21:25:15,803 | INFO | Building graph for timestep 25
2026-06-30 21:25:15,933 | INFO | Graph built successfully | Nodes: 594 | Edges: 559
2026-06-30 21:25:15,934 | INFO | Snapshot 25 validated.
2026-06-30 21:25:15,970 | INFO | Detected 177 communities.
2026-06-30 21:25:15,972 | INFO | Building graph for timestep 26
2026-06-30 21:25:16,086 | INFO | Graph built successfully | Nodes: 517 | Edges: 346
2026-06-30 21:25:16,087 | INFO | Snapshot 26 validated.
2026-06-30 21:25:16,108 | INFO | Detected 182 communities.
2026-06-30 21:25:16,109 | INFO | Building graph for timestep 27
2026-06-30 21:25:16,158 | INFO | Graph built successfully | Nodes: 206 | Edges: 58
2026-06-30 21:25:16,159 | INFO | Snapshot 27 validated.
2026-06-30 21:25:16,167 | INFO | Detected 149 communities.
2026-06-30 21:25:16,168 | INFO | Building graph for timestep 28
2026-06-30 21:25:16,238 | INFO | Graph built successfully | Nodes: 284 | Edges: 150
2026-06-30 21:25:16,238 | INFO | Snapshot 28 validated.
2026-06-30 21:25:16,251 | INFO | Detected 142 communities.
2026-06-30 21:25:16,252 | INFO | Building graph for timestep 29
2026-06-30 21:25:16,498 | INFO | Graph built successfully | Nodes: 1174 | Edges: 911
2026-06-30 21:25:16,499 | INFO | Snapshot 29 validated.
2026-06-30 21:25:16,555 | INFO | Detected 296 communities.
2026-06-30 21:25:16,557 | INFO | Building graph for timestep 30
2026-06-30 21:25:16,671 | INFO | Graph built successfully | Nodes: 524 | Edges: 372
2026-06-30 21:25:16,672 | INFO | Snapshot 30 validated.
2026-06-30 21:25:16,697 | INFO | Detected 171 communities.
2026-06-30 21:25:16,699 | INFO | Building graph for timestep 31
2026-06-30 21:25:16,868 | INFO | Graph built successfully | Nodes: 710 | Edges: 522
2026-06-30 21:25:16,869 | INFO | Snapshot 31 validated.
2026-06-30 21:25:16,906 | INFO | Detected 234 communities.
2026-06-30 21:25:16,908 | INFO | Building graph for timestep 32
2026-06-30 21:25:17,177 | INFO | Graph built successfully | Nodes: 1323 | Edges: 997
2026-06-30 21:25:17,178 | INFO | Snapshot 32 validated.
2026-06-30 21:25:17,261 | INFO | Detected 403 communities.
2026-06-30 21:25:17,263 | INFO | Building graph for timestep 33
2026-06-30 21:25:17,362 | INFO | Graph built successfully | Nodes: 441 | Edges: 429
2026-06-30 21:25:17,362 | INFO | Snapshot 33 validated.
2026-06-30 21:25:17,379 | INFO | Detected 56 communities.
2026-06-30 21:25:17,380 | INFO | Building graph for timestep 34
2026-06-30 21:25:17,493 | INFO | Graph built successfully | Nodes: 515 | Edges: 427
2026-06-30 21:25:17,493 | INFO | Snapshot 34 validated.
2026-06-30 21:25:17,520 | INFO | Detected 149 communities.
2026-06-30 21:25:17,522 | INFO | Building graph for timestep 35
2026-06-30 21:25:17,800 | INFO | Graph built successfully | Nodes: 1341 | Edges: 1002
2026-06-30 21:25:17,801 | INFO | Snapshot 35 validated.
2026-06-30 21:25:17,939 | INFO | Detected 464 communities.
2026-06-30 21:25:17,941 | INFO | Building graph for timestep 36
2026-06-30 21:25:18,285 | INFO | Graph built successfully | Nodes: 1708 | Edges: 1148
2026-06-30 21:25:18,286 | INFO | Snapshot 36 validated.
2026-06-30 21:25:18,385 | INFO | Detected 687 communities.
2026-06-30 21:25:18,388 | INFO | Building graph for timestep 37
2026-06-30 21:25:18,497 | INFO | Graph built successfully | Nodes: 498 | Edges: 423
2026-06-30 21:25:18,497 | INFO | Snapshot 37 validated.
2026-06-30 21:25:18,525 | INFO | Detected 124 communities.
2026-06-30 21:25:18,526 | INFO | Building graph for timestep 38
2026-06-30 21:25:18,689 | INFO | Graph built successfully | Nodes: 756 | Edges: 653
2026-06-30 21:25:18,690 | INFO | Snapshot 38 validated.
2026-06-30 21:25:18,729 | INFO | Detected 158 communities.
2026-06-30 21:25:18,731 | INFO | Building graph for timestep 39
2026-06-30 21:25:18,978 | INFO | Graph built successfully | Nodes: 1183 | Edges: 1055
2026-06-30 21:25:18,979 | INFO | Snapshot 39 validated.
2026-06-30 21:25:19,068 | INFO | Detected 211 communities.
2026-06-30 21:25:19,070 | INFO | Building graph for timestep 40
2026-06-30 21:25:19,320 | INFO | Graph built successfully | Nodes: 1211 | Edges: 1180
2026-06-30 21:25:19,321 | INFO | Snapshot 40 validated.
2026-06-30 21:25:19,400 | INFO | Detected 325 communities.
2026-06-30 21:25:19,402 | INFO | Building graph for timestep 41
2026-06-30 21:25:19,636 | INFO | Graph built successfully | Nodes: 1132 | Edges: 1048
2026-06-30 21:25:19,637 | INFO | Snapshot 41 validated.
2026-06-30 21:25:19,704 | INFO | Detected 337 communities.
2026-06-30 21:25:19,706 | INFO | Building graph for timestep 42
2026-06-30 21:25:20,136 | INFO | Graph built successfully | Nodes: 2154 | Edges: 1443
2026-06-30 21:25:20,137 | INFO | Snapshot 42 validated.
2026-06-30 21:25:20,271 | INFO | Detected 1003 communities.
2026-06-30 21:25:20,275 | INFO | Building graph for timestep 43
2026-06-30 21:25:20,553 | INFO | Graph built successfully | Nodes: 1370 | Edges: 935
2026-06-30 21:25:20,554 | INFO | Snapshot 43 validated.
2026-06-30 21:25:20,620 | INFO | Detected 531 communities.
2026-06-30 21:25:20,623 | INFO | Building graph for timestep 44
2026-06-30 21:25:20,944 | INFO | Graph built successfully | Nodes: 1591 | Edges: 1497
2026-06-30 21:25:20,945 | INFO | Snapshot 44 validated.
2026-06-30 21:25:21,037 | INFO | Detected 269 communities.
2026-06-30 21:25:21,040 | INFO | Building graph for timestep 45
2026-06-30 21:25:21,297 | INFO | Graph built successfully | Nodes: 1221 | Edges: 1346
2026-06-30 21:25:21,298 | INFO | Snapshot 45 validated.
2026-06-30 21:25:21,369 | INFO | Detected 246 communities.
2026-06-30 21:25:21,372 | INFO | Building graph for timestep 46
2026-06-30 21:25:21,522 | INFO | Graph built successfully | Nodes: 712 | Edges: 388
2026-06-30 21:25:21,522 | INFO | Snapshot 46 validated.
2026-06-30 21:25:21,553 | INFO | Detected 378 communities.
2026-06-30 21:25:21,555 | INFO | Building graph for timestep 47
2026-06-30 21:25:21,734 | INFO | Graph built successfully | Nodes: 846 | Edges: 822
2026-06-30 21:25:21,735 | INFO | Snapshot 47 validated.
2026-06-30 21:25:21,774 | INFO | Detected 203 communities.
2026-06-30 21:25:21,775 | INFO | Building graph for timestep 48
2026-06-30 21:25:21,879 | INFO | Graph built successfully | Nodes: 471 | Edges: 371
2026-06-30 21:25:21,879 | INFO | Snapshot 48 validated.
2026-06-30 21:25:21,897 | INFO | Detected 156 communities.
2026-06-30 21:25:21,899 | INFO | Building graph for timestep 49
2026-06-30 21:25:22,004 | INFO | Graph built successfully | Nodes: 476 | Edges: 415
2026-06-30 21:25:22,004 | INFO | Snapshot 49 validated.
2026-06-30 21:25:22,028 | INFO | Detected 103 communities.
2026-06-30 21:25:22,029 | INFO | Built 49 graphs.

In [21]:
manager.save_graphs()

CONVERT TO PyG

In [22]:
from src.graph.converter import GraphConverter

pyg = GraphConverter.to_pyg(
    manager.get_snapshot(20)
)

/Users/apple/dev/EvoFinGraph/src/graph/converter.py:36: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:256.)
  x = torch.tensor([

In [23]:
pyg

Data(x=[900, 165], edge_index=[2, 613], y=[900])

In [24]:
"""graph validator test"""
from src.community.validator import GraphValidator

for timestep in manager.graphs:

    GraphValidator.validate(
        manager.graphs[timestep]
    )

2026-06-30 21:25:32,306 | INFO | Snapshot 1 validated.
2026-06-30 21:25:32,307 | INFO | Snapshot 2 validated.
2026-06-30 21:25:32,309 | INFO | Snapshot 3 validated.
2026-06-30 21:25:32,310 | INFO | Snapshot 4 validated.
2026-06-30 21:25:32,311 | INFO | Snapshot 5 validated.
2026-06-30 21:25:32,312 | INFO | Snapshot 6 validated.
2026-06-30 21:25:32,313 | INFO | Snapshot 7 validated.
2026-06-30 21:25:32,314 | INFO | Snapshot 8 validated.
2026-06-30 21:25:32,315 | INFO | Snapshot 9 validated.
2026-06-30 21:25:32,316 | INFO | Snapshot 10 validated.
2026-06-30 21:25:32,317 | INFO | Snapshot 11 validated.
2026-06-30 21:25:32,317 | INFO | Snapshot 12 validated.
2026-06-30 21:25:32,318 | INFO | Snapshot 13 validated.
2026-06-30 21:25:32,318 | INFO | Snapshot 14 validated.
2026-06-30 21:25:32,319 | INFO | Snapshot 15 validated.
2026-06-30 21:25:32,320 | INFO | Snapshot 16 validated.
2026-06-30 21:25:32,320 | INFO | Snapshot 17 validated.
2026-06-30 21:25:32,320 | INFO | Snapshot 18 validated.
2026-06-30 21:25:32,321 | INFO | Snapshot 19 validated.
2026-06-30 21:25:32,321 | INFO | Snapshot 20 validated.
2026-06-30 21:25:32,322 | INFO | Snapshot 21 validated.
2026-06-30 21:25:32,322 | INFO | Snapshot 22 validated.
2026-06-30 21:25:32,323 | INFO | Snapshot 23 validated.
2026-06-30 21:25:32,323 | INFO | Snapshot 24 validated.
2026-06-30 21:25:32,324 | INFO | Snapshot 25 validated.
2026-06-30 21:25:32,325 | INFO | Snapshot 26 validated.
2026-06-30 21:25:32,325 | INFO | Snapshot 27 validated.
2026-06-30 21:25:32,326 | INFO | Snapshot 28 validated.
2026-06-30 21:25:32,327 | INFO | Snapshot 29 validated.
2026-06-30 21:25:32,327 | INFO | Snapshot 30 validated.
2026-06-30 21:25:32,328 | INFO | Snapshot 31 validated.
2026-06-30 21:25:32,329 | INFO | Snapshot 32 validated.
2026-06-30 21:25:32,329 | INFO | Snapshot 33 validated.
2026-06-30 21:25:32,330 | INFO | Snapshot 34 validated.
2026-06-30 21:25:32,330 | INFO | Snapshot 35 validated.
2026-06-30 21:25:32,331 | INFO | Snapshot 36 validated.
2026-06-30 21:25:32,332 | INFO | Snapshot 37 validated.
2026-06-30 21:25:32,332 | INFO | Snapshot 38 validated.
2026-06-30 21:25:32,333 | INFO | Snapshot 39 validated.
2026-06-30 21:25:32,334 | INFO | Snapshot 40 validated.
2026-06-30 21:25:32,334 | INFO | Snapshot 41 validated.
2026-06-30 21:25:32,335 | INFO | Snapshot 42 validated.
2026-06-30 21:25:32,336 | INFO | Snapshot 43 validated.
2026-06-30 21:25:32,337 | INFO | Snapshot 44 validated.
2026-06-30 21:25:32,341 | INFO | Snapshot 45 validated.
2026-06-30 21:25:32,344 | INFO | Snapshot 46 validated.
2026-06-30 21:25:32,346 | INFO | Snapshot 47 validated.
2026-06-30 21:25:32,346 | INFO | Snapshot 48 validated.
2026-06-30 21:25:32,347 | INFO | Snapshot 49 validated.

community detection

In [25]:
pip install python-louvain

Requirement already satisfied: python-louvain in /Users/apple/dev/EvoFinGraph/.venv/lib/python3.13/site-packages (0.16)
Requirement already satisfied: networkx in /Users/apple/dev/EvoFinGraph/.venv/lib/python3.13/site-packages (from python-louvain) (3.6.1)
Requirement already satisfied: numpy in /Users/apple/dev/EvoFinGraph/.venv/lib/python3.13/site-packages (from python-louvain) (2.5.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [26]:
"""community detection test"""
from src.community.detector import CommunityDetector

partition = CommunityDetector.detect(
    manager.get_snapshot(20)
)

2026-06-30 21:25:38,728 | INFO | Detected 327 communities.

transaction_id

↓

community_id

In [27]:
list(partition.items())[:10]

[(np.float64(209556175.0), 0),
 (np.float64(52934000.0), 1),
 (np.float64(37574467.0), 2),
 (np.float64(209972191.0), 2),
 (np.float64(73339227.0), 3),
 (np.float64(209837677.0), 4),
 (np.float64(5286455.0), 5),
 (np.float64(209826974.0), 15),
 (np.float64(210644361.0), 7),
 (np.float64(25642291.0), 7)]

In [28]:
graph = manager.get_snapshot(20)

node = list(graph.nodes())[0]

graph.nodes[node]

{'label': 0,
 'timestep': 20,
 'features': array([-0.17203984,  0.93356565, -0.09138345,  4.15516838, -0.04387455,
         3.57693649,  0.24271234, -0.16364521, -0.16868463, -0.04839205,
        -0.1659324 ,  0.63094145,  2.41400531, -0.0429553 , -0.01328161,
        -0.05251233, -0.17052874, -0.17259332, -0.17514801,  0.88705787,
         0.88455653, -0.13973186, -0.04025147, -0.05126814, -0.15316482,
         0.59769528,  1.65113477, -0.13973366, -0.04023953, -0.05126763,
        -0.15316452,  0.5977823 ,  1.65113037, -0.02466883, -0.03127097,
        -0.02304367, -0.02621462, -1.14757025, -0.18360513, -0.22720599,
         0.8351729 ,  0.59142966, -0.21488731,  0.90466207,  2.1080308 ,
        -0.22719348,  0.32920799,  0.44292184, -0.225085  ,  0.91885592,
         2.08257608, -0.39192924,  2.40298603,  2.12224136,  0.6660601 ,
         0.84799233,  0.81788927, -0.03909367, -0.07282871, -0.05658159,
        -0.06116722,  0.92347298,  0.92301071, -0.03908894, -0.07280981,
        -0.05656919, -0.06115659,  0.9235163 ,  0.92311013, -0.01703168,
        -0.03002624, -0.01764012, -0.0150709 , -0.14076322, -0.14033462,
        -0.09517862,  0.71885865,  0.76082871,  0.72829512,  1.13352668,
         1.1359467 , -0.05876867,  0.29202552,  0.31443482,  0.30540381,
         1.12558961,  1.12803803,  0.41329071,  1.62739033,  1.88146141,
         1.64156161,  1.13552275,  1.1352787 , -0.17108508, -0.060026  ,
        -0.04130366, -0.18379374,  0.60904536, -0.14552183, -0.2314754 ,
        -0.24666057, -0.08182634, -0.24207342, -0.55396519, -0.541569  ,
        -0.16654995,  0.94093884,  1.20710636,  0.46334167, -1.38429949,
        -1.58534275, -1.09633569,  0.7874347 ,  1.69570063, -0.73481159,
         1.18115195,  0.88703971, -0.1164246 ,  1.41154075,  0.55808475,
        -0.09237596,  0.90020955,  1.42694436, -0.09314473,  2.6918927 ,
         2.04274236,  1.68742212, -1.83431063, -2.02845019, -0.12319812,
         2.93007336,  3.78547148,  3.38308468, -1.1596488 , -1.16012886,
        -0.22623713, -0.33735736, -0.27605535, -0.27651023, -0.97573751,
        -0.97523656, -0.04789898, -0.14125018, -0.08295904, -0.09606633,
        -1.01596337, -1.01623043, -0.96890287, -0.89842627,  0.15320933,
        -1.07188529,  1.4881129 ,  1.48793248,  0.1382544 ,  2.16266737,
         2.69605185,  2.33826667, -0.97907377, -0.97855605, -0.09888874,
        -0.08749016, -0.08467423, -0.14059708,  1.51969962,  1.52139948]),
 'community': 0}

In [29]:
from collections import Counter

Counter(partition.values())

Counter({3: 39,
         4: 34,
         21: 34,
         15: 33,
         24: 30,
         91: 30,
         17: 29,
         29: 28,
         23: 26,
         10: 25,
         11: 24,
         14: 24,
         7: 23,
         19: 23,
         28: 17,
         22: 16,
         2: 15,
         8: 15,
         86: 15,
         57: 11,
         45: 10,
         84: 10,
         12: 9,
         26: 9,
         46: 6,
         1: 5,
         40: 5,
         166: 5,
         48: 4,
         59: 4,
         97: 4,
         217: 4,
         13: 3,
         62: 3,
         69: 3,
         78: 3,
         108: 3,
         126: 3,
         142: 3,
         161: 3,
         25: 2,
         34: 2,
         35: 2,
         47: 2,
         50: 2,
         58: 2,
         68: 2,
         95: 2,
         104: 2,
         106: 2,
         116: 2,
         122: 2,
         153: 2,
         159: 2,
         160: 2,
         174: 2,
         196: 2,
         227: 2,
         237: 2,
         243: 2,
         253: 2,
         259: 2,
         322: 2,
         0: 1,
         5: 1,
         9: 1,
         16: 1,
         18: 1,
         20: 1,
         27: 1,
         30: 1,
         31: 1,
         32: 1,
         36: 1,
         37: 1,
         38: 1,
         39: 1,
         41: 1,
         43: 1,
         44: 1,
         49: 1,
         51: 1,
         52: 1,
         53: 1,
         54: 1,
         55: 1,
         56: 1,
         60: 1,
         61: 1,
         63: 1,
         65: 1,
         66: 1,
         67: 1,
         70: 1,
         71: 1,
         72: 1,
         73: 1,
         75: 1,
         76: 1,
         77: 1,
         79: 1,
         80: 1,
         81: 1,
         82: 1,
         83: 1,
         85: 1,
         87: 1,
         88: 1,
         89: 1,
         90: 1,
         92: 1,
         93: 1,
         94: 1,
         96: 1,
         98: 1,
         99: 1,
         100: 1,
         101: 1,
         102: 1,
         103: 1,
         105: 1,
         107: 1,
         109: 1,
         110: 1,
         111: 1,
         112: 1,
         113: 1,
         114: 1,
         115: 1,
         117: 1,
         118: 1,
         119: 1,
         120: 1,
         121: 1,
         123: 1,
         124: 1,
         125: 1,
         127: 1,
         128: 1,
         129: 1,
         130: 1,
         131: 1,
         132: 1,
         133: 1,
         134: 1,
         135: 1,
         136: 1,
         137: 1,
         138: 1,
         139: 1,
         140: 1,
         141: 1,
         143: 1,
         144: 1,
         145: 1,
         146: 1,
         147: 1,
         148: 1,
         149: 1,
         150: 1,
         151: 1,
         152: 1,
         154: 1,
         155: 1,
         156: 1,
         157: 1,
         158: 1,
         162: 1,
         163: 1,
         164: 1,
         165: 1,
         167: 1,
         168: 1,
         169: 1,
         170: 1,
         171: 1,
         172: 1,
         173: 1,
         175: 1,
         176: 1,
         177: 1,
         178: 1,
         179: 1,
         180: 1,
         181: 1,
         182: 1,
         183: 1,
         184: 1,
         185: 1,
         186: 1,
         187: 1,
         188: 1,
         189: 1,
         190: 1,
         191: 1,
         192: 1,
         193: 1,
         194: 1,
         195: 1,
         197: 1,
         198: 1,
         199: 1,
         200: 1,
         201: 1,
         202: 1,
         203: 1,
         204: 1,
         205: 1,
         206: 1,
         207: 1,
         208: 1,
         209: 1,
         210: 1,
         211: 1,
         212: 1,
         213: 1,
         214: 1,
         215: 1,
         216: 1,
         218: 1,
         219: 1,
         220: 1,
         221: 1,
         222: 1,
         223: 1,
         224: 1,
         225: 1,
         226: 1,
         228: 1,
         229: 1,
         230: 1,
         231: 1,
         232: 1,
         233: 1,
         234: 1,
         235: 1,
         236: 1,
         238: 1,
         239: 1,
         240: 1,
         241: 1,
         242: 1,
         244: 1,
         245: 1,
         246: 1,
         247: 1,
         248: 1,
         249: 1,
         250: 1,
         251: 1,
         252: 1,
         254: 1,
         255: 1,
         256: 1,
         257: 1,
         258: 1,
         260: 1,
         261: 1,
         262: 1,
         263: 1,
         264: 1,
         265: 1,
         266: 1,
         267: 1,
         268: 1,
         269: 1,
         270: 1,
         271: 1,
         272: 1,
         273: 1,
         274: 1,
         275: 1,
         276: 1,
         277: 1,
         278: 1,
         279: 1,
         280: 1,
         281: 1,
         282: 1,
         283: 1,
         284: 1,
         285: 1,
         286: 1,
         287: 1,
         288: 1,
         289: 1,
         290: 1,
         291: 1,
         292: 1,
         293: 1,
         294: 1,
         295: 1,
         296: 1,
         297: 1,
         298: 1,
         299: 1,
         300: 1,
         301: 1,
         302: 1,
         303: 1,
         304: 1,
         305: 1,
         306: 1,
         307: 1,
         308: 1,
         309: 1,
         310: 1,
         311: 1,
         312: 1,
         313: 1,
         314: 1,
         315: 1,
         316: 1,
         317: 1,
         318: 1,
         319: 1,
         320: 1,
         321: 1,
         323: 1,
         324: 1,
         325: 1,
         326: 1,
         64: 1,
         33: 1,
         6: 1,
         42: 1,
         74: 1})

COMMUNITY STATS

In [30]:
from src.community.evolution import CommunityEvolution

summary = CommunityEvolution.summarize(
    manager.get_snapshot(20)
)

summary.head()

   timestep  community  size
0        20          0     1
1        20          1     5
2        20          2    15
3        20          3    39
4        20          4    34

In [31]:
community_tables = []

for timestep in manager.graphs:

    graph = manager.get_snapshot(
        timestep
    )

    CommunityDetector.detect(graph)

    community_tables.append(

        CommunityEvolution.summarize(
            graph
        )

    )

2026-06-30 21:25:54,024 | INFO | Detected 437 communities.
2026-06-30 21:25:54,085 | INFO | Detected 322 communities.
2026-06-30 21:25:54,151 | INFO | Detected 558 communities.
2026-06-30 21:25:54,229 | INFO | Detected 305 communities.
2026-06-30 21:25:54,338 | INFO | Detected 468 communities.
2026-06-30 21:25:54,361 | INFO | Detected 282 communities.
2026-06-30 21:25:54,439 | INFO | Detected 409 communities.
2026-06-30 21:25:54,501 | INFO | Detected 228 communities.
2026-06-30 21:25:54,544 | INFO | Detected 312 communities.
2026-06-30 21:25:54,730 | INFO | Detected 458 communities.
2026-06-30 21:25:54,767 | INFO | Detected 282 communities.
2026-06-30 21:25:54,795 | INFO | Detected 102 communities.
2026-06-30 21:25:54,854 | INFO | Detected 285 communities.
2026-06-30 21:25:54,886 | INFO | Detected 91 communities.
2026-06-30 21:25:54,924 | INFO | Detected 231 communities.
2026-06-30 21:25:54,947 | INFO | Detected 224 communities.
2026-06-30 21:25:54,993 | INFO | Detected 198 communities.
2026-06-30 21:25:55,010 | INFO | Detected 126 communities.
2026-06-30 21:25:55,056 | INFO | Detected 198 communities.
2026-06-30 21:25:55,107 | INFO | Detected 327 communities.
2026-06-30 21:25:55,140 | INFO | Detected 238 communities.
2026-06-30 21:25:55,244 | INFO | Detected 536 communities.
2026-06-30 21:25:55,311 | INFO | Detected 210 communities.
2026-06-30 21:25:55,383 | INFO | Detected 254 communities.
2026-06-30 21:25:55,418 | INFO | Detected 177 communities.
2026-06-30 21:25:55,443 | INFO | Detected 182 communities.
2026-06-30 21:25:55,452 | INFO | Detected 149 communities.
2026-06-30 21:25:55,466 | INFO | Detected 142 communities.
2026-06-30 21:25:55,528 | INFO | Detected 296 communities.
2026-06-30 21:25:55,558 | INFO | Detected 171 communities.
2026-06-30 21:25:55,596 | INFO | Detected 234 communities.
2026-06-30 21:25:55,685 | INFO | Detected 403 communities.
2026-06-30 21:25:55,703 | INFO | Detected 56 communities.
2026-06-30 21:25:55,731 | INFO | Detected 149 communities.
2026-06-30 21:25:55,817 | INFO | Detected 464 communities.
2026-06-30 21:25:55,924 | INFO | Detected 687 communities.
2026-06-30 21:25:55,954 | INFO | Detected 124 communities.
2026-06-30 21:25:55,996 | INFO | Detected 158 communities.
2026-06-30 21:25:56,094 | INFO | Detected 211 communities.
2026-06-30 21:25:56,176 | INFO | Detected 325 communities.
2026-06-30 21:25:56,246 | INFO | Detected 337 communities.
2026-06-30 21:25:56,385 | INFO | Detected 1003 communities.
2026-06-30 21:25:56,458 | INFO | Detected 531 communities.
2026-06-30 21:25:56,558 | INFO | Detected 269 communities.
2026-06-30 21:25:56,638 | INFO | Detected 246 communities.
2026-06-30 21:25:56,670 | INFO | Detected 378 communities.
2026-06-30 21:25:56,712 | INFO | Detected 203 communities.
2026-06-30 21:25:56,731 | INFO | Detected 156 communities.
2026-06-30 21:25:56,757 | INFO | Detected 103 communities.

In [32]:
community_df = pd.concat(
    community_tables,
    ignore_index=True
)

community_df.head()

   timestep  community  size
0         1          0   133
1         1          1    78
2         1          2    28
3         1          3   271
4         1          4     1

Table 3 for paper

In [33]:
community_df.to_csv(

"../outputs/community_summary.csv",

index=False

)

In [34]:
import src.config

print(src.config.__file__)

/Users/apple/dev/EvoFinGraph/src/config.py

In [35]:
dir(src.config)

['ALL_SNAPSHOTS',
 'CLASS_FILE',
 'COMMUNITY_MATCHING_WEIGHTS',
 'COMMUNITY_MATCH_THRESHOLD',
 'DATA_DIR',
 'DEV_SNAPSHOTS',
 'DOCS_DIR',
 'EDGE_FILE',
 'EXPORT_DIR',
 'FEATURE_FILE',
 'FIGURE_DIR',
 'METRIC_DIR',
 'MODEL_DIR',
 'NOTEBOOK_DIR',
 'OUTPUT_DIR',
 'PROCESSED_DATA_DIR',
 'PROJECT_ROOT',
 'Path',
 'RANDOM_STATE',
 'RAW_DATA_DIR',
 'SNAPSHOT_DIR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']

In [36]:
import os

print(os.getcwd())

/Users/apple/dev/EvoFinGraph/notebooks

In [37]:
from src.graph.manager import TemporalGraphManager

manager = TemporalGraphManager()

2026-06-30 21:26:12,953 | INFO | Loading processed dataset...
2026-06-30 21:26:25,096 | INFO | Dataset loaded successfully.

In [38]:
timesteps = range(1, 50)

manager.build_all(timesteps)

2026-06-30 21:26:27,914 | INFO | Building temporal graphs...
2026-06-30 21:26:27,915 | INFO | Building graph for timestep 1
2026-06-30 21:26:28,352 | INFO | Graph built successfully | Nodes: 2147 | Edges: 1924
2026-06-30 21:26:28,353 | INFO | Snapshot 1 validated.
2026-06-30 21:26:28,473 | INFO | Detected 437 communities.
2026-06-30 21:26:28,477 | INFO | Building graph for timestep 2
2026-06-30 21:26:28,721 | INFO | Graph built successfully | Nodes: 1117 | Edges: 858
2026-06-30 21:26:28,721 | INFO | Snapshot 2 validated.
2026-06-30 21:26:28,787 | INFO | Detected 322 communities.
2026-06-30 21:26:28,789 | INFO | Building graph for timestep 3
2026-06-30 21:26:29,064 | INFO | Graph built successfully | Nodes: 1279 | Edges: 727
2026-06-30 21:26:29,065 | INFO | Snapshot 3 validated.
2026-06-30 21:26:29,133 | INFO | Detected 558 communities.
2026-06-30 21:26:29,136 | INFO | Building graph for timestep 4
2026-06-30 21:26:29,451 | INFO | Graph built successfully | Nodes: 1440 | Edges: 1169
2026-06-30 21:26:29,452 | INFO | Snapshot 4 validated.
2026-06-30 21:26:29,532 | INFO | Detected 305 communities.
2026-06-30 21:26:29,535 | INFO | Building graph for timestep 5
2026-06-30 21:26:29,936 | INFO | Graph built successfully | Nodes: 1882 | Edges: 1491
2026-06-30 21:26:29,937 | INFO | Snapshot 5 validated.
2026-06-30 21:26:30,047 | INFO | Detected 468 communities.
2026-06-30 21:26:30,051 | INFO | Building graph for timestep 6
2026-06-30 21:26:30,164 | INFO | Graph built successfully | Nodes: 485 | Edges: 209
2026-06-30 21:26:30,165 | INFO | Snapshot 6 validated.
2026-06-30 21:26:30,188 | INFO | Detected 282 communities.
2026-06-30 21:26:30,189 | INFO | Building graph for timestep 7
2026-06-30 21:26:30,451 | INFO | Graph built successfully | Nodes: 1203 | Edges: 858
2026-06-30 21:26:30,452 | INFO | Snapshot 7 validated.
2026-06-30 21:26:30,526 | INFO | Detected 409 communities.
2026-06-30 21:26:30,528 | INFO | Building graph for timestep 8
2026-06-30 21:26:30,775 | INFO | Graph built successfully | Nodes: 1165 | Edges: 1044
2026-06-30 21:26:30,775 | INFO | Snapshot 8 validated.
2026-06-30 21:26:30,833 | INFO | Detected 228 communities.
2026-06-30 21:26:30,835 | INFO | Building graph for timestep 9
2026-06-30 21:26:31,005 | INFO | Graph built successfully | Nodes: 778 | Edges: 484
2026-06-30 21:26:31,006 | INFO | Snapshot 9 validated.
2026-06-30 21:26:31,046 | INFO | Detected 312 communities.
2026-06-30 21:26:31,048 | INFO | Building graph for timestep 10
2026-06-30 21:26:31,259 | INFO | Graph built successfully | Nodes: 972 | Edges: 538
2026-06-30 21:26:31,260 | INFO | Snapshot 10 validated.
2026-06-30 21:26:31,309 | INFO | Detected 458 communities.
2026-06-30 21:26:31,311 | INFO | Building graph for timestep 11
2026-06-30 21:26:31,485 | INFO | Graph built successfully | Nodes: 696 | Edges: 477
2026-06-30 21:26:31,486 | INFO | Snapshot 11 validated.
2026-06-30 21:26:31,522 | INFO | Detected 282 communities.
2026-06-30 21:26:31,524 | INFO | Building graph for timestep 12
2026-06-30 21:26:31,633 | INFO | Graph built successfully | Nodes: 506 | Edges: 446
2026-06-30 21:26:31,633 | INFO | Snapshot 12 validated.
2026-06-30 21:26:31,663 | INFO | Detected 102 communities.
2026-06-30 21:26:31,664 | INFO | Building graph for timestep 13
2026-06-30 21:26:31,835 | INFO | Graph built successfully | Nodes: 809 | Edges: 564
2026-06-30 21:26:31,836 | INFO | Snapshot 13 validated.
2026-06-30 21:26:31,883 | INFO | Detected 285 communities.
2026-06-30 21:26:31,885 | INFO | Building graph for timestep 14
2026-06-30 21:26:31,980 | INFO | Graph built successfully | Nodes: 417 | Edges: 350
2026-06-30 21:26:31,981 | INFO | Snapshot 14 validated.
2026-06-30 21:26:32,003 | INFO | Detected 91 communities.
2026-06-30 21:26:32,005 | INFO | Building graph for timestep 15
2026-06-30 21:26:32,144 | INFO | Graph built successfully | Nodes: 618 | Edges: 446
2026-06-30 21:26:32,145 | INFO | Snapshot 15 validated.
2026-06-30 21:26:32,179 | INFO | Detected 231 communities.
2026-06-30 21:26:32,181 | INFO | Building graph for timestep 16
2026-06-30 21:26:32,295 | INFO | Graph built successfully | Nodes: 530 | Edges: 334
2026-06-30 21:26:32,296 | INFO | Snapshot 16 validated.
2026-06-30 21:26:32,318 | INFO | Detected 224 communities.
2026-06-30 21:26:32,320 | INFO | Building graph for timestep 17
2026-06-30 21:26:32,488 | INFO | Graph built successfully | Nodes: 811 | Edges: 673
2026-06-30 21:26:32,489 | INFO | Snapshot 17 validated.
2026-06-30 21:26:32,530 | INFO | Detected 198 communities.
2026-06-30 21:26:32,531 | INFO | Building graph for timestep 18
2026-06-30 21:26:32,625 | INFO | Graph built successfully | Nodes: 389 | Edges: 275
2026-06-30 21:26:32,625 | INFO | Snapshot 18 validated.
2026-06-30 21:26:32,640 | INFO | Detected 126 communities.
2026-06-30 21:26:32,641 | INFO | Building graph for timestep 19
2026-06-30 21:26:32,802 | INFO | Graph built successfully | Nodes: 745 | Edges: 585
2026-06-30 21:26:32,803 | INFO | Snapshot 19 validated.
2026-06-30 21:26:32,846 | INFO | Detected 198 communities.
2026-06-30 21:26:32,848 | INFO | Building graph for timestep 20
2026-06-30 21:26:33,033 | INFO | Graph built successfully | Nodes: 900 | Edges: 613
2026-06-30 21:26:33,034 | INFO | Snapshot 20 validated.
2026-06-30 21:26:33,086 | INFO | Detected 327 communities.
2026-06-30 21:26:33,087 | INFO | Building graph for timestep 21
2026-06-30 21:26:33,227 | INFO | Graph built successfully | Nodes: 641 | Edges: 518
2026-06-30 21:26:33,228 | INFO | Snapshot 21 validated.
2026-06-30 21:26:33,258 | INFO | Detected 238 communities.
2026-06-30 21:26:33,260 | INFO | Building graph for timestep 22
2026-06-30 21:26:33,619 | INFO | Graph built successfully | Nodes: 1763 | Edges: 1537
2026-06-30 21:26:33,620 | INFO | Snapshot 22 validated.
2026-06-30 21:26:33,721 | INFO | Detected 536 communities.
2026-06-30 21:26:33,724 | INFO | Building graph for timestep 23
2026-06-30 21:26:33,970 | INFO | Graph built successfully | Nodes: 1187 | Edges: 1046
2026-06-30 21:26:33,970 | INFO | Snapshot 23 validated.
2026-06-30 21:26:34,033 | INFO | Detected 210 communities.
2026-06-30 21:26:34,036 | INFO | Building graph for timestep 24
2026-06-30 21:26:34,268 | INFO | Graph built successfully | Nodes: 1126 | Edges: 961
2026-06-30 21:26:34,269 | INFO | Snapshot 24 validated.
2026-06-30 21:26:34,337 | INFO | Detected 254 communities.
2026-06-30 21:26:34,339 | INFO | Building graph for timestep 25
2026-06-30 21:26:34,468 | INFO | Graph built successfully | Nodes: 594 | Edges: 559
2026-06-30 21:26:34,469 | INFO | Snapshot 25 validated.
2026-06-30 21:26:34,504 | INFO | Detected 177 communities.
2026-06-30 21:26:34,506 | INFO | Building graph for timestep 26
2026-06-30 21:26:34,619 | INFO | Graph built successfully | Nodes: 517 | Edges: 346
2026-06-30 21:26:34,620 | INFO | Snapshot 26 validated.
2026-06-30 21:26:34,641 | INFO | Detected 182 communities.
2026-06-30 21:26:34,643 | INFO | Building graph for timestep 27
2026-06-30 21:26:34,692 | INFO | Graph built successfully | Nodes: 206 | Edges: 58
2026-06-30 21:26:34,693 | INFO | Snapshot 27 validated.
2026-06-30 21:26:34,701 | INFO | Detected 149 communities.
2026-06-30 21:26:34,702 | INFO | Building graph for timestep 28
2026-06-30 21:26:34,771 | INFO | Graph built successfully | Nodes: 284 | Edges: 150
2026-06-30 21:26:34,771 | INFO | Snapshot 28 validated.
2026-06-30 21:26:34,784 | INFO | Detected 142 communities.
2026-06-30 21:26:34,785 | INFO | Building graph for timestep 29
2026-06-30 21:26:35,030 | INFO | Graph built successfully | Nodes: 1174 | Edges: 911
2026-06-30 21:26:35,030 | INFO | Snapshot 29 validated.
2026-06-30 21:26:35,087 | INFO | Detected 296 communities.
2026-06-30 21:26:35,090 | INFO | Building graph for timestep 30
2026-06-30 21:26:35,204 | INFO | Graph built successfully | Nodes: 524 | Edges: 372
2026-06-30 21:26:35,204 | INFO | Snapshot 30 validated.
2026-06-30 21:26:35,230 | INFO | Detected 171 communities.
2026-06-30 21:26:35,231 | INFO | Building graph for timestep 31
2026-06-30 21:26:35,384 | INFO | Graph built successfully | Nodes: 710 | Edges: 522
2026-06-30 21:26:35,385 | INFO | Snapshot 31 validated.
2026-06-30 21:26:35,422 | INFO | Detected 234 communities.
2026-06-30 21:26:35,424 | INFO | Building graph for timestep 32
2026-06-30 21:26:35,696 | INFO | Graph built successfully | Nodes: 1323 | Edges: 997
2026-06-30 21:26:35,696 | INFO | Snapshot 32 validated.
2026-06-30 21:26:35,779 | INFO | Detected 403 communities.
2026-06-30 21:26:35,781 | INFO | Building graph for timestep 33
2026-06-30 21:26:35,878 | INFO | Graph built successfully | Nodes: 441 | Edges: 429
2026-06-30 21:26:35,878 | INFO | Snapshot 33 validated.
2026-06-30 21:26:35,896 | INFO | Detected 56 communities.
2026-06-30 21:26:35,898 | INFO | Building graph for timestep 34
2026-06-30 21:26:36,009 | INFO | Graph built successfully | Nodes: 515 | Edges: 427
2026-06-30 21:26:36,010 | INFO | Snapshot 34 validated.
2026-06-30 21:26:36,034 | INFO | Detected 149 communities.
2026-06-30 21:26:36,035 | INFO | Building graph for timestep 35
2026-06-30 21:26:36,308 | INFO | Graph built successfully | Nodes: 1341 | Edges: 1002
2026-06-30 21:26:36,309 | INFO | Snapshot 35 validated.
2026-06-30 21:26:36,390 | INFO | Detected 464 communities.
2026-06-30 21:26:36,392 | INFO | Building graph for timestep 36
2026-06-30 21:26:36,729 | INFO | Graph built successfully | Nodes: 1708 | Edges: 1148
2026-06-30 21:26:36,730 | INFO | Snapshot 36 validated.
2026-06-30 21:26:36,830 | INFO | Detected 687 communities.
2026-06-30 21:26:36,832 | INFO | Building graph for timestep 37
2026-06-30 21:26:36,940 | INFO | Graph built successfully | Nodes: 498 | Edges: 423
2026-06-30 21:26:36,941 | INFO | Snapshot 37 validated.
2026-06-30 21:26:36,969 | INFO | Detected 124 communities.
2026-06-30 21:26:36,971 | INFO | Building graph for timestep 38
2026-06-30 21:26:37,133 | INFO | Graph built successfully | Nodes: 756 | Edges: 653
2026-06-30 21:26:37,133 | INFO | Snapshot 38 validated.
2026-06-30 21:26:37,176 | INFO | Detected 158 communities.
2026-06-30 21:26:37,179 | INFO | Building graph for timestep 39
2026-06-30 21:26:37,441 | INFO | Graph built successfully | Nodes: 1183 | Edges: 1055
2026-06-30 21:26:37,442 | INFO | Snapshot 39 validated.
2026-06-30 21:26:37,529 | INFO | Detected 211 communities.
2026-06-30 21:26:37,531 | INFO | Building graph for timestep 40
2026-06-30 21:26:37,787 | INFO | Graph built successfully | Nodes: 1211 | Edges: 1180
2026-06-30 21:26:37,788 | INFO | Snapshot 40 validated.
2026-06-30 21:26:37,866 | INFO | Detected 325 communities.
2026-06-30 21:26:37,868 | INFO | Building graph for timestep 41
2026-06-30 21:26:38,103 | INFO | Graph built successfully | Nodes: 1132 | Edges: 1048
2026-06-30 21:26:38,104 | INFO | Snapshot 41 validated.
2026-06-30 21:26:38,169 | INFO | Detected 337 communities.
2026-06-30 21:26:38,171 | INFO | Building graph for timestep 42
2026-06-30 21:26:38,596 | INFO | Graph built successfully | Nodes: 2154 | Edges: 1443
2026-06-30 21:26:38,597 | INFO | Snapshot 42 validated.
2026-06-30 21:26:38,727 | INFO | Detected 1003 communities.
2026-06-30 21:26:38,730 | INFO | Building graph for timestep 43
2026-06-30 21:26:39,008 | INFO | Graph built successfully | Nodes: 1370 | Edges: 935
2026-06-30 21:26:39,009 | INFO | Snapshot 43 validated.
2026-06-30 21:26:39,075 | INFO | Detected 531 communities.
2026-06-30 21:26:39,077 | INFO | Building graph for timestep 44
2026-06-30 21:26:39,397 | INFO | Graph built successfully | Nodes: 1591 | Edges: 1497
2026-06-30 21:26:39,398 | INFO | Snapshot 44 validated.
2026-06-30 21:26:39,489 | INFO | Detected 269 communities.
2026-06-30 21:26:39,492 | INFO | Building graph for timestep 45
2026-06-30 21:26:39,751 | INFO | Graph built successfully | Nodes: 1221 | Edges: 1346
2026-06-30 21:26:39,752 | INFO | Snapshot 45 validated.
2026-06-30 21:26:39,822 | INFO | Detected 246 communities.
2026-06-30 21:26:39,825 | INFO | Building graph for timestep 46
2026-06-30 21:26:39,973 | INFO | Graph built successfully | Nodes: 712 | Edges: 388
2026-06-30 21:26:39,974 | INFO | Snapshot 46 validated.
2026-06-30 21:26:40,003 | INFO | Detected 378 communities.
2026-06-30 21:26:40,005 | INFO | Building graph for timestep 47
2026-06-30 21:26:40,181 | INFO | Graph built successfully | Nodes: 846 | Edges: 822
2026-06-30 21:26:40,181 | INFO | Snapshot 47 validated.
2026-06-30 21:26:40,220 | INFO | Detected 203 communities.
2026-06-30 21:26:40,222 | INFO | Building graph for timestep 48
2026-06-30 21:26:40,325 | INFO | Graph built successfully | Nodes: 471 | Edges: 371
2026-06-30 21:26:40,326 | INFO | Snapshot 48 validated.
2026-06-30 21:26:40,347 | INFO | Detected 156 communities.
2026-06-30 21:26:40,349 | INFO | Building graph for timestep 49
2026-06-30 21:26:40,459 | INFO | Graph built successfully | Nodes: 476 | Edges: 415
2026-06-30 21:26:40,459 | INFO | Snapshot 49 validated.
2026-06-30 21:26:40,483 | INFO | Detected 103 communities.
2026-06-30 21:26:40,485 | INFO | Built 49 graphs.

In [39]:
graph = manager.get_snapshot(20)

graph

In [40]:
graph.number_of_nodes(), graph.number_of_edges()

(900, 613)

In [41]:
from src.community.detector import CommunityDetector

for graph in manager.graphs.values():
    CommunityDetector.detect(graph)

2026-06-30 21:26:53,851 | INFO | Detected 437 communities.
2026-06-30 21:26:53,912 | INFO | Detected 322 communities.
2026-06-30 21:26:53,976 | INFO | Detected 558 communities.
2026-06-30 21:26:54,056 | INFO | Detected 305 communities.
2026-06-30 21:26:54,161 | INFO | Detected 468 communities.
2026-06-30 21:26:54,459 | INFO | Detected 282 communities.
2026-06-30 21:26:54,538 | INFO | Detected 409 communities.
2026-06-30 21:26:54,603 | INFO | Detected 228 communities.
2026-06-30 21:26:54,644 | INFO | Detected 312 communities.
2026-06-30 21:26:54,691 | INFO | Detected 458 communities.
2026-06-30 21:26:54,728 | INFO | Detected 282 communities.
2026-06-30 21:26:54,762 | INFO | Detected 102 communities.
2026-06-30 21:26:54,810 | INFO | Detected 285 communities.
2026-06-30 21:26:54,833 | INFO | Detected 91 communities.
2026-06-30 21:26:54,867 | INFO | Detected 231 communities.
2026-06-30 21:26:54,893 | INFO | Detected 224 communities.
2026-06-30 21:26:54,938 | INFO | Detected 198 communities.
2026-06-30 21:26:54,954 | INFO | Detected 126 communities.
2026-06-30 21:26:55,001 | INFO | Detected 198 communities.
2026-06-30 21:26:55,058 | INFO | Detected 327 communities.
2026-06-30 21:26:55,089 | INFO | Detected 238 communities.
2026-06-30 21:26:55,191 | INFO | Detected 536 communities.
2026-06-30 21:26:55,254 | INFO | Detected 210 communities.
2026-06-30 21:26:55,325 | INFO | Detected 254 communities.
2026-06-30 21:26:55,365 | INFO | Detected 177 communities.
2026-06-30 21:26:55,395 | INFO | Detected 182 communities.
2026-06-30 21:26:55,405 | INFO | Detected 149 communities.
2026-06-30 21:26:55,421 | INFO | Detected 142 communities.
2026-06-30 21:26:55,481 | INFO | Detected 296 communities.
2026-06-30 21:26:55,507 | INFO | Detected 171 communities.
2026-06-30 21:26:55,543 | INFO | Detected 234 communities.
2026-06-30 21:26:55,629 | INFO | Detected 403 communities.
2026-06-30 21:26:55,646 | INFO | Detected 56 communities.
2026-06-30 21:26:55,670 | INFO | Detected 149 communities.
2026-06-30 21:26:55,754 | INFO | Detected 464 communities.
2026-06-30 21:26:55,855 | INFO | Detected 687 communities.
2026-06-30 21:26:55,885 | INFO | Detected 124 communities.
2026-06-30 21:26:55,925 | INFO | Detected 158 communities.
2026-06-30 21:26:56,016 | INFO | Detected 211 communities.
2026-06-30 21:26:56,094 | INFO | Detected 325 communities.
2026-06-30 21:26:56,160 | INFO | Detected 337 communities.
2026-06-30 21:26:56,294 | INFO | Detected 1003 communities.
2026-06-30 21:26:56,362 | INFO | Detected 531 communities.
2026-06-30 21:26:56,453 | INFO | Detected 269 communities.
2026-06-30 21:26:56,526 | INFO | Detected 246 communities.
2026-06-30 21:26:56,556 | INFO | Detected 378 communities.
2026-06-30 21:26:56,596 | INFO | Detected 203 communities.
2026-06-30 21:26:56,617 | INFO | Detected 156 communities.
2026-06-30 21:26:56,639 | INFO | Detected 103 communities.

In [42]:
node, attrs = next(iter(graph.nodes(data=True)))

print(node)
print(attrs.keys())

41402314.0
dict_keys(['label', 'timestep', 'features', 'community'])

In [43]:
print(attrs)

{'label': 0, 'timestep': 49, 'features': array([-1.29660189e-01,  1.24769340e+00,  1.57359458e+00,  2.72945572e+00,
        2.14175781e-01,  2.98990082e+00, -6.15837941e-02, -1.63621978e-01,
       -1.46527538e-01,  2.61134952e-03, -1.64813292e-01,  7.09416880e-01,
        2.76421721e-01,  2.20225203e-01, -1.32816149e-02, -5.68541283e-02,
       -1.52445800e-01, -1.63713312e-01, -1.69425668e-01, -1.13315898e-01,
       -1.87051242e-01, -1.39731849e-01, -1.48573494e-01, -8.00350586e-02,
       -1.55639860e-01, -1.29593558e-01, -3.65509925e-01, -1.39733649e-01,
       -1.48568781e-01, -8.00345284e-02, -1.55639828e-01, -1.29504915e-01,
       -3.65384991e-01, -2.46688307e-02, -3.12497279e-02, -2.30168426e-02,
       -2.62140413e-02,  2.85377399e-01, -6.20989425e-01, -2.27215446e-01,
       -2.33346434e-01, -6.97522885e-02, -2.34225397e-01, -8.86040622e-01,
       -8.93588512e-01, -2.27203324e-01, -2.37206817e-01, -8.94752540e-02,
       -2.35173613e-01, -9.01525649e-01, -8.91326832e-01, -4.13787706e-01,
        1.29432757e+00,  1.12824135e+00,  1.95987644e-02, -4.10728596e-01,
       -6.86473308e-01, -3.91510735e-02, -1.72726749e-01, -1.63060532e-01,
       -1.60900122e-01, -3.05775812e-01, -1.24240296e-01, -3.91463580e-02,
       -1.72715696e-01, -1.63049194e-01, -1.60893235e-01, -3.05751378e-01,
       -1.24181308e-01, -1.70316759e-02, -3.00262353e-02, -1.76401196e-02,
       -1.50709000e-02, -1.40763222e-01, -1.40334624e-01, -9.54026893e-02,
       -2.63560525e-01, -2.50233129e-01, -2.63536578e-01, -2.50297715e-01,
       -3.19393702e-01, -5.90130548e-02, -2.61500349e-01, -2.54801809e-01,
       -2.59014178e-01, -2.60887493e-01, -3.38693450e-01, -2.93887599e-01,
        3.08433775e-03, -2.72646771e-01, -4.15359200e-01, -5.87086149e-02,
        9.86258453e-02, -1.71083376e-01, -5.72417370e-02, -2.61845469e-02,
       -1.80214878e-01,  1.23806546e-01,  2.95577125e-01,  1.64052547e+00,
        1.65688808e+00, -8.27220940e-02,  1.65629008e+00,  1.88646891e+00,
        1.88350382e+00, -1.47522342e-01,  2.11847736e-01,  3.67983295e-01,
        7.23085639e-02,  3.07559693e-01,  2.65074408e-01, -3.62376653e-02,
        1.30112835e+00,  1.10740299e+00,  1.27288234e+00, -5.65917871e-01,
       -5.39077868e-01, -1.16424604e-01,  1.83912176e+00,  1.09300794e+00,
        2.69524075e-01,  9.03938891e-01,  8.81809797e-01, -9.31447270e-02,
       -1.05387813e-01, -6.98167915e-02, -9.43536012e-02,  7.03898109e-01,
        1.15168287e+00, -1.24704311e-01, -1.18554904e-02, -8.74613330e-02,
       -1.24530355e-01,  1.47312418e-01,  1.46421996e-01,  1.52491842e+00,
        1.61524342e+00,  1.32874868e-01,  1.47923094e+00,  6.44504986e-01,
        4.98186788e-01, -1.55629617e-01,  2.73976493e+00,  1.58204843e+00,
        1.42073202e+00,  5.00757261e-01,  4.26259949e-01, -9.68902875e-01,
        1.19242068e+00,  9.29903107e-01,  5.47080219e-01, -3.43532548e-01,
       -2.97322464e-01, -2.16814361e-01,  2.92379599e+00,  1.35680397e+00,
        1.04566261e+00,  7.80138801e-01,  5.75015625e-01, -9.88887367e-02,
        4.12345744e-01,  3.27505783e-01,  1.09229133e-01, -7.25130802e-01,
       -4.20180586e-01]), 'community': 0}

In [44]:
from src.community.matcher import CommunityMatcher

graph = manager.get_snapshot(20)

communities = CommunityMatcher.get_communities(graph)

print(f"Communities: {len(communities)}")

Communities: 327

In [45]:
import importlib
import src.community.matcher

importlib.reload(src.community.matcher)

from src.community.matcher import CommunityMatcher

In [46]:
dir(CommunityMatcher)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'community_similarity',
 'compute_average_degree_similarity',
 'compute_density_similarity',
 'compute_fraud_ratio_similarity',
 'compute_member_overlap',
 'get_communities',
 'match']

In [47]:
import src.community.matcher
print(src.community.matcher.__file__)

from src.community.matcher import CommunityMatcher
print(dir(CommunityMatcher))

/Users/apple/dev/EvoFinGraph/src/community/matcher.py
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', 'community_similarity', 'compute_average_degree_similarity', 'compute_density_similarity', 'compute_fraud_ratio_similarity', 'compute_member_overlap', 'get_communities', 'match']

IGNORE ALL THE ABOVE BUT HTE BELOW ONE IS IMPORTANT TEST FOR TRACKER.PY

In [48]:
from src.community.tracker import CommunityTracker

tracker = CommunityTracker()

tracker.track(manager.graphs)

len(tracker.community_map)

14235

In [55]:
list(tracker.community_map.items())[:10]

[((1, 0),
  {'pcid': 0,
   'previous_community': None,
   'current_community': 0,
   'score': 1.0}),
 ((1, 1),
  {'pcid': 1,
   'previous_community': None,
   'current_community': 1,
   'score': 1.0}),
 ((1, 2),
  {'pcid': 2,
   'previous_community': None,
   'current_community': 2,
   'score': 1.0}),
 ((1, 3),
  {'pcid': 3,
   'previous_community': None,
   'current_community': 3,
   'score': 1.0}),
 ((1, 4),
  {'pcid': 4,
   'previous_community': None,
   'current_community': 4,
   'score': 1.0}),
 ((1, 5),
  {'pcid': 5,
   'previous_community': None,
   'current_community': 5,
   'score': 1.0}),
 ((1, 6),
  {'pcid': 6,
   'previous_community': None,
   'current_community': 6,
   'score': 1.0}),
 ((1, 7),
  {'pcid': 7,
   'previous_community': None,
   'current_community': 7,
   'score': 1.0}),
 ((1, 8),
  {'pcid': 8,
   'previous_community': None,
   'current_community': 8,
   'score': 1.0}),
 ((1, 9),
  {'pcid': 9,
   'previous_community': None,
   'current_community': 9,
   'score': 1.0})]

In [59]:
"""test for timeline.py"""
import importlib

import src.community.timeline

importlib.reload(src.community.timeline)

from src.community.timeline import CommunityTimeline
from src.community.timeline import CommunityTimeline

timeline = CommunityTimeline()

timeline.build(
    tracker,
    manager.graphs,
)

2026-06-30 21:41:04,748 | INFO | Built 14235 community timelines.

In [60]:
len(timeline.timelines)

14235

In [61]:
"""this is a fraud ring test"""
timeline.get_timeline(0)

[{'timestep': 1,
  'graph': <networkx.classes.digraph.DiGraph at 0x11ced5090>,
  'community': 0,
  'previous_community': None,
  'score': 1.0}]

In [62]:
timeline.summarize()[:5]

[{'pcid': 0,
  'birth': 1,
  'death': 1,
  'lifetime': 1,
  'persistence': 1,
  'snapshots': 1},
 {'pcid': 1,
  'birth': 1,
  'death': 1,
  'lifetime': 1,
  'persistence': 1,
  'snapshots': 1},
 {'pcid': 2,
  'birth': 1,
  'death': 1,
  'lifetime': 1,
  'persistence': 1,
  'snapshots': 1},
 {'pcid': 3,
  'birth': 1,
  'death': 1,
  'lifetime': 1,
  'persistence': 1,
  'snapshots': 1},
 {'pcid': 4,
  'birth': 1,
  'death': 1,
  'lifetime': 1,
  'persistence': 1,
  'snapshots': 1}]