In [ ]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [ ]:
import sys
print(sys.executable)
print(sys.version)

/Users/apple/dev/EvoFinGraph/.venv/bin/python
3.13.7 (main, Aug 14 2025, 11:12:11) [Clang 17.0.0 (clang-1700.0.13.3)]

In [ ]:
from src.models.base import BaseModel

In [ ]:
BaseModel

src.models.base.BaseModel

In [ ]:
import importlib

import src.config
import src.pipeline.builder
import src.graph.converter
import src.models.graphsage

importlib.reload(src.pipeline.builder)
importlib.reload(src.graph.converter)
importlib.reload(src.models.graphsage)

from src.pipeline.builder import EvoFinGraphPipeline
from src.graph.converter import GraphConverter
from src.models.graphsage import GraphSAGEModel

In [ ]:
pipeline = EvoFinGraphPipeline()

pipeline.build()

2026-07-20 13:39:33,385 | INFO | Loading processed dataset...
2026-07-20 13:39:45,513 | INFO | Dataset loaded successfully.
2026-07-20 13:39:45,515 | INFO | Building temporal graphs...
2026-07-20 13:39:45,515 | INFO | Building graph for timestep 20
2026-07-20 13:39:45,700 | INFO | Graph built successfully | Nodes: 900 | Edges: 613
2026-07-20 13:39:45,700 | INFO | Snapshot 20 validated.
2026-07-20 13:39:45,752 | INFO | Detected 327 communities.
2026-07-20 13:39:45,754 | INFO | Building graph for timestep 21
2026-07-20 13:39:45,891 | INFO | Graph built successfully | Nodes: 641 | Edges: 518
2026-07-20 13:39:45,892 | INFO | Snapshot 21 validated.
2026-07-20 13:39:45,922 | INFO | Detected 238 communities.
2026-07-20 13:39:45,924 | INFO | Building graph for timestep 22
2026-07-20 13:39:46,292 | INFO | Graph built successfully | Nodes: 1763 | Edges: 1537
2026-07-20 13:39:46,293 | INFO | Snapshot 22 validated.
2026-07-20 13:39:46,394 | INFO | Detected 536 communities.
2026-07-20 13:39:46,397 | INFO | Building graph for timestep 23
2026-07-20 13:39:46,640 | INFO | Graph built successfully | Nodes: 1187 | Edges: 1046
2026-07-20 13:39:46,641 | INFO | Snapshot 23 validated.
2026-07-20 13:39:46,708 | INFO | Detected 210 communities.
2026-07-20 13:39:46,710 | INFO | Building graph for timestep 24
2026-07-20 13:39:46,944 | INFO | Graph built successfully | Nodes: 1126 | Edges: 961
2026-07-20 13:39:46,946 | INFO | Snapshot 24 validated.
2026-07-20 13:39:47,019 | INFO | Detected 254 communities.
2026-07-20 13:39:47,021 | INFO | Built 5 graphs.
2026-07-20 13:40:11,125 | INFO | Built 1037 community timelines.

In [ ]:
pipeline.summary()

============================================================
EVOFINGRAPH PIPELINE
============================================================
Snapshots              : 5
Tracked Communities    : 1037
Feature Matrix Shape   : (528, 16)
============================================================

In [ ]:
feature_matrix = pipeline.feature_matrix

feature_matrix.head()

,pcid,timestep,community,growth_rate,density_change,degree_change,fraud_growth,clustering_change,feature_drift,variance_drift,lifetime,persistence,average_match_score,node_churn,structural_stability,is_fraud_community
0,6,21,11,-0.151515,0.178571,-0.043478,1.357143,0.0,4.610801,0.295710,2,0.4,0.859100,1.848485,0.931084,1
1,11,21,18,0.666667,-0.169231,0.530612,-1.000000,0.0,4.278830,0.730030,2,0.4,0.903350,2.666667,0.810845,0
2,15,21,9,0.000000,0.000000,0.000000,0.000000,0.0,9.080104,0.000000,3,0.6,0.915467,2.000000,1.000000,0
3,15,22,457,0.000000,0.000000,0.000000,0.000000,0.0,4.331653,0.000000,3,0.6,0.915467,2.000000,1.000000,0
4,18,21,87,-0.391304,0.642857,0.008117,0.000000,0.0,3.258021,0.064171,4,0.8,0.793975,1.608696,0.821699,1

In [ ]:
from src.models.data import ModelData

X_train, X_test, y_train, y_test = ModelData.prepare(
    feature_matrix
)

In [ ]:
"""Train logistic regression model"""
from src.models.logistic import LogisticModel

model = LogisticModel()

model.fit(
    X_train,
    y_train,
)

In [ ]:
importance = model.feature_importance(
    X_train.columns
)

importance

{'fraud_growth': np.float64(1.1035315533366545),
 'density_change': np.float64(0.6986070380543582),
 'structural_stability': np.float64(-0.47786163297257883),
 'feature_drift': np.float64(-0.38054042777938185),
 'degree_change': np.float64(0.24794286441997868),
 'node_churn': np.float64(0.08202755449643861),
 'growth_rate': np.float64(0.06628974916498764),
 'variance_drift': np.float64(0.0638143691491139),
 'clustering_change': np.float64(-0.014967009727762057)}

EVALUATION FOLDER'S METRICS TESTING

In [ ]:
from src.evaluation.metrics import EvaluationMetrics

predictions = model.predict(
    X_test
)

probabilities = model.predict_proba(
    X_test
)

metrics = EvaluationMetrics.compute(

    y_test,

    predictions,

    probabilities,

)

metrics

{'accuracy': 0.6698113207547169,
 'precision': 0.3877551020408163,
 'recall': 0.7916666666666666,
 'f1': 0.5205479452054794,
 'roc_auc': 0.8724593495934958}

In [ ]:
from src.evaluation.report import EvaluationReport

In [ ]:
report = EvaluationReport()

In [ ]:
report.add(
    "Logistic Regression",
    metrics,
)

In [ ]:
report.summary()

============================================================
MODEL COMPARISON
============================================================
                 model  accuracy  precision    recall        f1   roc_auc
0  Logistic Regression  0.669811   0.387755  0.791667  0.520548  0.872459

                 model  accuracy  precision    recall        f1   roc_auc
0  Logistic Regression  0.669811   0.387755  0.791667  0.520548  0.872459

XGBOOST TESTING

In [ ]:
from src.models.xgboost import XGBoostModel

xgb = XGBoostModel()

xgb.fit(
    X_train,
    y_train,
)

In [ ]:
"""Predict"""
xgb_predictions = xgb.predict(
    X_test
)

xgb_probabilities = xgb.predict_proba(
    X_test
)

In [ ]:
from src.evaluation.metrics import EvaluationMetrics

xgb_metrics = EvaluationMetrics.compute(

    y_test,

    xgb_predictions,

    xgb_probabilities,

)

xgb_metrics

{'accuracy': 0.839622641509434,
 'precision': 0.6666666666666666,
 'recall': 0.5833333333333334,
 'f1': 0.6222222222222222,
 'roc_auc': 0.853658536585366}

In [ ]:
importance = xgb.feature_importance(
    X_train.columns
)

importance

{'feature_drift': np.float32(0.237506),
 'variance_drift': np.float32(0.13049889),
 'fraud_growth': np.float32(0.12957232),
 'density_change': np.float32(0.12261081),
 'structural_stability': np.float32(0.10358988),
 'growth_rate': np.float32(0.095519386),
 'degree_change': np.float32(0.09538253),
 'node_churn': np.float32(0.08532023),
 'clustering_change': np.float32(0.0)}

In [ ]:
logistic_predictions = model.predict(
    X_test
)

logistic_probabilities = model.predict_proba(
    X_test
)

In [ ]:
from src.evaluation.metrics import EvaluationMetrics

logistic_metrics = EvaluationMetrics.compute(

    y_test,

    logistic_predictions,

    logistic_probabilities,

)

logistic_metrics

{'accuracy': 0.6698113207547169,
 'precision': 0.3877551020408163,
 'recall': 0.7916666666666666,
 'f1': 0.5205479452054794,
 'roc_auc': 0.8724593495934958}

In [ ]:
from src.evaluation.report import EvaluationReport

report = EvaluationReport()

report.add(

    "Logistic Regression",

    logistic_metrics,

)

report.add(

    "XGBoost",

    xgb_metrics,

)

comparison = report.summary()

comparison

============================================================
MODEL COMPARISON
============================================================
                 model  accuracy  precision    recall        f1   roc_auc
1              XGBoost  0.839623   0.666667  0.583333  0.622222  0.853659
0  Logistic Regression  0.669811   0.387755  0.791667  0.520548  0.872459

                 model  accuracy  precision    recall        f1   roc_auc
1              XGBoost  0.839623   0.666667  0.583333  0.622222  0.853659
0  Logistic Regression  0.669811   0.387755  0.791667  0.520548  0.872459

In [ ]:
report.rank("f1")

                 model  accuracy  precision    recall        f1   roc_auc
1              XGBoost  0.839623   0.666667  0.583333  0.622222  0.853659
0  Logistic Regression  0.669811   0.387755  0.791667  0.520548  0.872459

In [ ]:
import pandas as pd

comparison = pd.DataFrame({

    "Logistic": model.feature_importance(
        X_train.columns
    ),

    "XGBoost": xgb.feature_importance(
        X_train.columns
    ),

})

comparison

                      Logistic   XGBoost
fraud_growth          1.103532  0.129572
density_change        0.698607  0.122611
structural_stability -0.477862  0.103590
feature_drift        -0.380540  0.237506
degree_change         0.247943  0.095383
node_churn            0.082028  0.085320
growth_rate           0.066290  0.095519
variance_drift        0.063814  0.130499
clustering_change    -0.014967  0.000000

In [ ]:
"""testing graph converter to implement graphsage"""
from src.graph.converter import GraphConverter

graph = pipeline.get_graph(20)

data = GraphConverter.to_pyg(graph)

data

/Users/apple/dev/EvoFinGraph/src/graph/converter.py:115: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:256.)
  x = torch.tensor(

Data(
  x=[900, 165],
  edge_index=[2, 1226],
  y=[900],
  community=[900],
  node_mapping={
    209556175.0=0,
    52934000.0=1,
    37574467.0=2,
    209972191.0=3,
    73339227.0=4,
    209837677.0=5,
    5286455.0=6,
    209826974.0=7,
    210644361.0=8,
    25642291.0=9,
    209952987.0=10,
    209952974.0=11,
    211086336.0=12,
    209724105.0=13,
    209045031.0=14,
    210640906.0=15,
    209681259.0=16,
    209118488.0=17,
    209794811.0=18,
    209487402.0=19,
    209678521.0=20,
    209533787.0=21,
    209918381.0=22,
    209537331.0=23,
    209905828.0=24,
    210192146.0=25,
    1275118.0=26,
    4659656.0=27,
    209091416.0=28,
    209692891.0=29,
    107697436.0=30,
    209518228.0=31,
    211078002.0=32,
    209688652.0=33,
    209921231.0=34,
    209824867.0=35,
    209673949.0=36,
    209842048.0=37,
    8182823.0=38,
    209798865.0=39,
    1552384.0=40,
    209818962.0=41,
    209045727.0=42,
    209674270.0=43,
    209892725.0=44,
    58114564.0=45,
    208927896.0=46,
    210570269.0=47,
    209050993.0=48,
    209923303.0=49,
    210488058.0=50,
    208914286.0=51,
    210709803.0=52,
    210943575.0=53,
    209865519.0=54,
    209084673.0=55,
    210640426.0=56,
    70553579.0=57,
    208992025.0=58,
    209973945.0=59,
    209785341.0=60,
    209810063.0=61,
    209060715.0=62,
    209722457.0=63,
    209539924.0=64,
    209802609.0=65,
    210623843.0=66,
    210830766.0=67,
    209683152.0=68,
    209499354.0=69,
    210620987.0=70,
    209968540.0=71,
    209918443.0=72,
    209575028.0=73,
    210646799.0=74,
    210624714.0=75,
    209054310.0=76,
    209706044.0=77,
    209685472.0=78,
    210660376.0=79,
    114134551.0=80,
    209905405.0=81,
    209865237.0=82,
    209797492.0=83,
    210233819.0=84,
    210519382.0=85,
    209723629.0=86,
    209709679.0=87,
    210628279.0=88,
    210369097.0=89,
    209972181.0=90,
    9275272.0=91,
    209064416.0=92,
    110276377.0=93,
    209971737.0=94,
    32023895.0=95,
    209866894.0=96,
    140042478.0=97,
    209045711.0=98,
    209836059.0=99,
    209799189.0=100,
    209922231.0=101,
    210230813.0=102,
    209815595.0=103,
    54335231.0=104,
    209813841.0=105,
    210642702.0=106,
    209060600.0=107,
    209804657.0=108,
    209485498.0=109,
    209799194.0=110,
    209058193.0=111,
    208944877.0=112,
    25154813.0=113,
    209723672.0=114,
    211084916.0=115,
    209923003.0=116,
    2272609.0=117,
    209922935.0=118,
    209922929.0=119,
    209537361.0=120,
    43447701.0=121,
    208921748.0=122,
    209562939.0=123,
    210624700.0=124,
    209966110.0=125,
    210660956.0=126,
    209922528.0=127,
    208900651.0=128,
    211086885.0=129,
    208935742.0=130,
    209682872.0=131,
    208911970.0=132,
    118790722.0=133,
    209834452.0=134,
    209479787.0=135,
    23002760.0=136,
    209539892.0=137,
    209597151.0=138,
    208970579.0=139,
    209889755.0=140,
    210628188.0=141,
    210713464.0=142,
    1533983.0=143,
    211169275.0=144,
    209972877.0=145,
    209030336.0=146,
    209129597.0=147,
    209867187.0=148,
    211152178.0=149,
    209515365.0=150,
    209485038.0=151,
    209555134.0=152,
    209722184.0=153,
    209514218.0=154,
    209522524.0=155,
    87632830.0=156,
    209161715.0=157,
    209052413.0=158,
    209054636.0=159,
    209798859.0=160,
    209798851.0=161,
    209785327.0=162,
    209057696.0=163,
    210624703.0=164,
    190440214.0=165,
    209796911.0=166,
    209527608.0=167,
    211083061.0=168,
    2107102.0=169,
    209498993.0=170,
    53158431.0=171,
    209673899.0=172,
    94429635.0=173,
    208959966.0=174,
    209150797.0=175,
    209799187.0=176,
    209982244.0=177,
    209523687.0=178,
    209723687.0=179,
    209836829.0=180,
    211181064.0=181,
    209052730.0=182,
    209975318.0=183,
    209539876.0=184,
    209539728.0=185,
    209964071.0=186,
    209673948.0=187,
    209678295.0=188,
    209045719.0=189,
    209674266.0=190,
    209922538.0=191,
    209866533.0=192,
    209866360.0=193,
    210570551.0=194,
    209922222.0=195,
    209680209.0=196,
    210943583.0=197,
    209864872.0=198,
    210573258.0=199,
    209669184.0=200,
    209505350.0=201,
    209046118.0=202,
    209541751.0=203,
    209482814.0=204,
    209921572.0=205,
    209867496.0=206,
    209867494.0=207,
    210636318.0=208,
    209479777.0=209,
    210662684.0=210,
    163919062.0=211,
    209499242.0=212,
    209499240.0=213,
    209537525.0=214,
    55070629.0=215,
    209525408.0=216,
    25154839.0=217,
    25154862.0=218,
    104483720.0=219,
    209923327.0=220,
    210624706.0=221,
    209080442.0=222,
    209961356.0=223,
    210708869.0=224,
    209565381.0=225,
    209921515.0=226,
    54618280.0=227,
    209809733.0=228,
    208970977.0=229,
    210625257.0=230,
    210639090.0=231,
    209982240.0=232,
    210846805.0=233,
    209521902.0=234,
    51394168.0=235,
    209814125.0=236,
    209722177.0=237,
    209045705.0=238,
    210624713.0=239,
    209485480.0=240,
    43531652.0=241,
    209525755.0=242,
    209922530.0=243,
    209485040.0=244,
    209809720.0=245,
    209844295.0=246,
    22226403.0=247,
    208969679.0=248,
    211170015.0=249,
    51394132.0=250,
    209596325.0=251,
    209531144.0=252,
    209555593.0=253,
    209485137.0=254,
    209673883.0=255,
    209673652.0=256,
    209485057.0=257,
    209485610.0=258,
    209805172.0=259,
    210625509.0=260,
    209051931.0=261,
    209782043.0=262,
    209518121.0=263,
    8203186.0=264,
    209973678.0=265,
    209532554.0=266,
    208921478.0=267,
    209672239.0=268,
    209518125.0=269,
    209499458.0=270,
    209842056.0=271,
    209836334.0=272,
    209515363.0=273,
    209806741.0=274,
    208947780.0=275,
    209485044.0=276,
    208901445.0=277,
    40168070.0=278,
    209093960.0=279,
    209118496.0=280,
    209050020.0=281,
    208960717.0=282,
    209596327.0=283,
    209531348.0=284,
    210642506.0=285,
    210387347.0=286,
    209526041.0=287,
    209695001.0=288,
    209695805.0=289,
    210624712.0=290,
    210646674.0=291,
    210638486.0=292,
    209970528.0=293,
    209701336.0=294,
    209485497.0=295,
    209805537.0=296,
    209524165.0=297,
    209498992.0=298,
    210624696.0=299,
    209514213.0=300,
    209118257.0=301,
    209723625.0=302,
    209518732.0=303,
    211083408.0=304,
    50104984.0=305,
    209830521.0=306,
    208904532.0=307,
    209077871.0=308,
    209160064.0=309,
    210957067.0=310,
    210368118.0=311,
    209970510.0=312,
    210636338.0=313,
    210930666.0=314,
    209482592.0=315,
    210635499.0=316,
    209521884.0=317,
    209867201.0=318,
    209893004.0=319,
    209921551.0=320,
    209722453.0=321,
    208969173.0=322,
    209710576.0=323,
    209490127.0=324,
    209838463.0=325,
    210507246.0=326,
    209695412.0=327,
    209817923.0=328,
    209531334.0=329,
    209839480.0=330,
    209510541.0=331,
    95117503.0=332,
    209490129.0=333,
    115333920.0=334,
    210201894.0=335,
    209826714.0=336,
    208900640.0=337,
    209972888.0=338,
    209522339.0=339,
    210627653.0=340,
    3566826.0=341,
    209906191.0=342,
    209946183.0=343,
    8521092.0=344,
    209681283.0=345,
    209478840.0=346,
    109730813.0=347,
    210574441.0=348,
    210628292.0=349,
    14944210.0=350,
    209478843.0=351,
    211090711.0=352,
    211119485.0=353,
    209694846.0=354,
    208960226.0=355,
    210626820.0=356,
    52704100.0=357,
    211092116.0=358,
    209822485.0=359,
    209704313.0=360,
    209587871.0=361,
    209974893.0=362,
    209519073.0=363,
    208902769.0=364,
    209043823.0=365,
    209806124.0=366,
    209671004.0=367,
    209809064.0=368,
    211085325.0=369,
    209541479.0=370,
    83525154.0=371,
    121459474.0=372,
    209922529.0=373,
    143959970.0=374,
    209596331.0=375,
    209833927.0=376,
    209946505.0=377,
    20002498.0=378,
    209525931.0=379,
    209596738.0=380,
    77782188.0=381,
    210670745.0=382,
    208909714.0=383,
    210624882.0=384,
    211078006.0=385,
    209053064.0=386,
    209065141.0=387,
    209895646.0=388,
    209118635.0=389,
    209723662.0=390,
    209499380.0=391,
    209042752.0=392,
    209671389.0=393,
    209499638.0=394,
    209535127.0=395,
    53118222.0=396,
    209478837.0=397,
    209946514.0=398,
    209922228.0=399,
    209812911.0=400,
    209493623.0=401,
    209493620.0=402,
    83525157.0=403,
    83525156.0=404,
    208904726.0=405,
    209037145.0=406,
    138359626.0=407,
    209946527.0=408,
    209139836.0=409,
    210373225.0=410,
    209050851.0=411,
    208961542.0=412,
    210394281.0=413,
    211095800.0=414,
    209695451.0=415,
    9801858.0=416,
    58865613.0=417,
    150067970.0=418,
    209923005.0=419,
    58918333.0=420,
    210624701.0=421,
    209918748.0=422,
    209478839.0=423,
    209705074.0=424,
    58913964.0=425,
    209867499.0=426,
    209798862.0=427,
    209522313.0=428,
    209796394.0=429,
    209834203.0=430,
    208931358.0=431,
    210625512.0=432,
    210366116.0=433,
    209822487.0=434,
    209533785.0=435,
    209044304.0=436,
    209523197.0=437,
    51018142.0=438,
    30886080.0=439,
    210507234.0=440,
    210636771.0=441,
    209088168.0=442,
    209970537.0=443,
    209070934.0=444,
    209843368.0=445,
    209530380.0=446,
    209138562.0=447,
    209972861.0=448,
    208913476.0=449,
    120843705.0=450,
    209554638.0=451,
    209823054.0=452,
    209822489.0=453,
    209970545.0=454,
    209722170.0=455,
    209125712.0=456,
    209479724.0=457,
    27653479.0=458,
    209499243.0=459,
    209051209.0=460,
    209480688.0=461,
    77775952.0=462,
    210403106.0=463,
    3783350.0=464,
    209818218.0=465,
    209512730.0=466,
    210624884.0=467,
    208928467.0=468,
    209797619.0=469,
    209942282.0=470,
    209061548.0=471,
    209811752.0=472,
    209537369.0=473,
    209510523.0=474,
    209970515.0=475,
    209961366.0=476,
    210709810.0=477,
    209796391.0=478,
    211120424.0=479,
    26303286.0=480,
    209521882.0=481,
    209680771.0=482,
    209533786.0=483,
    51619871.0=484,
    209922541.0=485,
    210646327.0=486,
    209517884.0=487,
    209878477.0=488,
    209487354.0=489,
    209866556.0=490,
    209530780.0=491,
    209531124.0=492,
    209523824.0=493,
    210637584.0=494,
    210642271.0=495,
    209837589.0=496,
    209685497.0=497,
    209037166.0=498,
    208909658.0=499,
    210397358.0=500,
    209531037.0=501,
    208910380.0=502,
    211092325.0=503,
    209118261.0=504,
    210644771.0=505,
    33428696.0=506,
    209515367.0=507,
    209590611.0=508,
    209532564.0=509,
    209571418.0=510,
    211087780.0=511,
    209801054.0=512,
    22995113.0=513,
    210636309.0=514,
    209028819.0=515,
    209825447.0=516,
    208911102.0=517,
    209689418.0=518,
    208931411.0=519,
    209972906.0=520,
    208991798.0=521,
    25155718.0=522,
    209029156.0=523,
    209485035.0=524,
    208909650.0=525,
    209488132.0=526,
    209522039.0=527,
    209867207.0=528,
    209867206.0=529,
    46932930.0=530,
    209486126.0=531,
    210636396.0=532,
    209522297.0=533,
    209517742.0=534,
    209811519.0=535,
    209486818.0=536,
    209077867.0=537,
    209511361.0=538,
    209511358.0=539,
    209052468.0=540,
    209706038.0=541,
    58112623.0=542,
    209521972.0=543,
    208904961.0=544,
    209045471.0=545,
    209814467.0=546,
    210672250.0=547,
    210643790.0=548,
    209086584.0=549,
    209946889.0=550,
    209531708.0=551,
    209965106.0=552,
    209522042.0=553,
    209674268.0=554,
    209798844.0=555,
    211087789.0=556,
    209571107.0=557,
    209807092.0=558,
    209694819.0=559,
    209518754.0=560,
    140975824.0=561,
    209488424.0=562,
    209479773.0=563,
    210624705.0=564,
    208921741.0=565,
    209064129.0=566,
    209677633.0=567,
    209053077.0=568,
    209867501.0=569,
    208944591.0=570,
    208948658.0=571,
    210508856.0=572,
    208928076.0=573,
    209516184.0=574,
    211091078.0=575,
    209794828.0=576,
    209046121.0=577,
    210367157.0=578,
    210396663.0=579,
    209722450.0=580,
    850645.0=581,
    209482853.0=582,
    209682060.0=583,
    210640850.0=584,
    209970517.0=585,
    208993106.0=586,
    81834567.0=587,
    209067879.0=588,
    208997267.0=589,
    209065945.0=590,
    53329746.0=591,
    209701749.0=592,
    209485488.0=593,
    209485047.0=594,
    209681263.0=595,
    209805526.0=596,
    209798861.0=597,
    209680861.0=598,
    209682855.0=599,
    54268187.0=600,
    209701751.0=601,
    210233475.0=602,
    209045696.0=603,
    96382692.0=604,
    210975906.0=605,
    209866541.0=606,
    210642699.0=607,
    209709674.0=608,
    211119690.0=609,
    209796397.0=610,
    209722461.0=611,
    209515844.0=612,
    209879340.0=613,
    209796165.0=614,
    208925967.0=615,
    209483930.0=616,
    209522745.0=617,
    209030341.0=618,
    209517738.0=619,
    211083395.0=620,
    209723655.0=621,
    210628282.0=622,
    208963301.0=623,
    209577997.0=624,
    209682852.0=625,
    209922226.0=626,
    74075669.0=627,
    210652905.0=628,
    211088967.0=629,
    209052847.0=630,
    209512149.0=631,
    209521989.0=632,
    209051283.0=633,
    209921981.0=634,
    209596024.0=635,
    209541747.0=636,
    209979041.0=637,
    209499350.0=638,
    209480690.0=639,
    209093705.0=640,
    209555131.0=641,
    209522272.0=642,
    208959034.0=643,
    209970507.0=644,
    209561689.0=645,
    209522541.0=646,
    210643786.0=647,
    209522526.0=648,
    208967566.0=649,
    210943573.0=650,
    211083401.0=651,
    209031542.0=652,
    210365374.0=653,
    209499246.0=654,
    209062970.0=655,
    209669583.0=656,
    83525158.0=657,
    210278727.0=658,
    210640144.0=659,
    210646334.0=660,
    210412384.0=661,
    209979679.0=662,
    209683499.0=663,
    209068753.0=664,
    209522305.0=665,
    209681254.0=666,
    210627663.0=667,
    209751853.0=668,
    209727886.0=669,
    210643804.0=670,
    209053086.0=671,
    122707305.0=672,
    210635984.0=673,
    210635981.0=674,
    210206969.0=675,
    209526176.0=676,
    209685477.0=677,
    209521887.0=678,
    85694207.0=679,
    210389656.0=680,
    209527133.0=681,
    210366127.0=682,
    208931582.0=683,
    210320960.0=684,
    209539733.0=685,
    209522304.0=686,
    209063361.0=687,
    208917612.0=688,
    208969303.0=689,
    209525247.0=690,
    209050327.0=691,
    210871896.0=692,
    209681387.0=693,
    209539886.0=694,
    210638488.0=695,
    209061557.0=696,
    209063357.0=697,
    209682050.0=698,
    210380262.0=699,
    209682048.0=700,
    208992305.0=701,
    42834266.0=702,
    210638701.0=703,
    209522533.0=704,
    163784570.0=705,
    209691967.0=706,
    209866555.0=707,
    209053093.0=708,
    209485037.0=709,
    210368815.0=710,
    210370556.0=711,
    209568490.0=712,
    24051859.0=713,
    208948655.0=714,
    106087814.0=715,
    209051294.0=716,
    209695804.0=717,
    209677582.0=718,
    50942668.0=719,
    210370539.0=720,
    211083096.0=721,
    209798867.0=722,
    209923309.0=723,
    208948278.0=724,
    209531135.0=725,
    34570609.0=726,
    210645872.0=727,
    210232205.0=728,
    53285642.0=729,
    209803038.0=730,
    209679681.0=731,
    210638695.0=732,
    210248451.0=733,
    209674257.0=734,
    209971709.0=735,
    209503437.0=736,
    209482841.0=737,
    209522034.0=738,
    209842041.0=739,
    210628998.0=740,
    210232606.0=741,
    60114653.0=742,
    80279852.0=743,
    209522528.0=744,
    209052474.0=745,
    209140981.0=746,
    209962612.0=747,
    209729963.0=748,
    209809451.0=749,
    209839780.0=750,
    209825801.0=751,
    209947246.0=752,
    209971173.0=753,
    209075128.0=754,
    208969667.0=755,
    145056524.0=756,
    209805539.0=757,
    208931388.0=758,
    210664815.0=759,
    209525915.0=760,
    209695448.0=761,
    20030272.0=762,
    209683500.0=763,
    209844170.0=764,
    209681391.0=765,
    209756766.0=766,
    209526419.0=767,
    209922542.0=768,
    208948283.0=769,
    209126997.0=770,
    209905144.0=771,
    209531343.0=772,
    209030643.0=773,
    209949491.0=774,
    209051194.0=775,
    209054313.0=776,
    209918743.0=777,
    209722188.0=778,
    209515366.0=779,
    209945629.0=780,
    209945016.0=781,
    209704311.0=782,
    209526055.0=783,
    210638473.0=784,
    38494021.0=785,
    209050859.0=786,
    209890590.0=787,
    209052396.0=788,
    209043819.0=789,
    211088962.0=790,
    209561676.0=791,
    210635497.0=792,
    209040244.0=793,
    210508548.0=794,
    209069871.0=795,
    209923009.0=796,
    210643424.0=797,
    209971727.0=798,
    209809062.0=799,
    209704312.0=800,
    209722458.0=801,
    58918503.0=802,
    209084102.0=803,
    210403108.0=804,
    208947999.0=805,
    210655664.0=806,
    209050862.0=807,
    81827657.0=808,
    209971407.0=809,
    208930291.0=810,
    209730304.0=811,
    211088954.0=812,
    209482870.0=813,
    209825743.0=814,
    209970505.0=815,
    209922227.0=816,
    209922229.0=817,
    210636827.0=818,
    209059761.0=819,
    210368812.0=820,
    107364854.0=821,
    210944633.0=822,
    209054965.0=823,
    209922540.0=824,
    211090714.0=825,
    211089021.0=826,
    209125646.0=827,
    209924804.0=828,
    209687545.0=829,
    209685076.0=830,
    209950868.0=831,
    210639339.0=832,
    208930307.0=833,
    210510738.0=834,
    209141540.0=835,
    133212313.0=836,
    210642754.0=837,
    209807087.0=838,
    210380697.0=839,
    209753752.0=840,
    210239451.0=841,
    209524153.0=842,
    209044340.0=843,
    211184525.0=844,
    209894140.0=845,
    209838453.0=846,
    209701748.0=847,
    209961474.0=848,
    210657608.0=849,
    209064452.0=850,
    209680989.0=851,
    209531711.0=852,
    211101452.0=853,
    209972893.0=854,
    209803040.0=855,
    209970520.0=856,
    60102676.0=857,
    208931421.0=858,
    209922515.0=859,
    209678300.0=860,
    209923295.0=861,
    209521880.0=862,
    210628484.0=863,
    211087476.0=864,
    209067185.0=865,
    209045026.0=866,
    209946182.0=867,
    209522014.0=868,
    209828537.0=869,
    209678569.0=870,
    209888701.0=871,
    211089437.0=872,
    210448457.0=873,
    210405839.0=874,
    209527121.0=875,
    98922712.0=876,
    209071105.0=877,
    210642727.0=878,
    209825437.0=879,
    209490521.0=880,
    63472808.0=881,
    209084078.0=882,
    210368819.0=883,
    209509084.0=884,
    209124207.0=885,
    162721834.0=886,
    208969189.0=887,
    209539327.0=888,
    209949241.0=889,
    209922223.0=890,
    210636785.0=891,
    209039347.0=892,
    211085853.0=893,
    209921280.0=894,
    210506329.0=895,
    208952465.0=896,
    210368107.0=897,
    209946892.0=898,
    210710768.0=899,
  },
  reverse_mapping={
    0=209556175.0,
    1=52934000.0,
    2=37574467.0,
    3=209972191.0,
    4=73339227.0,
    5=209837677.0,
    6=5286455.0,
    7=209826974.0,
    8=210644361.0,
    9=25642291.0,
    10=209952987.0,
    11=209952974.0,
    12=211086336.0,
    13=209724105.0,
    14=209045031.0,
    15=210640906.0,
    16=209681259.0,
    17=209118488.0,
    18=209794811.0,
    19=209487402.0,
    20=209678521.0,
    21=209533787.0,
    22=209918381.0,
    23=209537331.0,
    24=209905828.0,
    25=210192146.0,
    26=1275118.0,
    27=4659656.0,
    28=209091416.0,
    29=209692891.0,
    30=107697436.0,
    31=209518228.0,
    32=211078002.0,
    33=209688652.0,
    34=209921231.0,
    35=209824867.0,
    36=209673949.0,
    37=209842048.0,
    38=8182823.0,
    39=209798865.0,
    40=1552384.0,
    41=209818962.0,
    42=209045727.0,
    43=209674270.0,
    44=209892725.0,
    45=58114564.0,
    46=208927896.0,
    47=210570269.0,
    48=209050993.0,
    49=209923303.0,
    50=210488058.0,
    51=208914286.0,
    52=210709803.0,
    53=210943575.0,
    54=209865519.0,
    55=209084673.0,
    56=210640426.0,
    57=70553579.0,
    58=208992025.0,
    59=209973945.0,

In [ ]:
print(data.community.shape)

print(data.timestep)

print(len(data.node_mapping))

print(data.reverse_mapping[0])

torch.Size([900])
20
900
209556175.0

In [ ]:
import importlib
import src.graph.converter

importlib.reload(src.graph.converter)

In [ ]:
from src.graph.converter import GraphConverter

graph = pipeline.get_graph(20)

data = GraphConverter.to_pyg(graph)

print(data.num_communities)

327

In [ ]:
from src.graph.converter import GraphConverter

pyg_graphs = GraphConverter.convert_all(
    pipeline.graphs
)

In [ ]:
pyg_graphs.keys()

dict_keys([20, 21, 22, 23, 24])

In [ ]:
pyg_graphs[20]

Data(
  x=[900, 165],
  edge_index=[2, 1226],
  y=[900],
  community=[900],
  node_mapping={
    209556175.0=0,
    52934000.0=1,
    37574467.0=2,
    209972191.0=3,
    73339227.0=4,
    209837677.0=5,
    5286455.0=6,
    209826974.0=7,
    210644361.0=8,
    25642291.0=9,
    209952987.0=10,
    209952974.0=11,
    211086336.0=12,
    209724105.0=13,
    209045031.0=14,
    210640906.0=15,
    209681259.0=16,
    209118488.0=17,
    209794811.0=18,
    209487402.0=19,
    209678521.0=20,
    209533787.0=21,
    209918381.0=22,
    209537331.0=23,
    209905828.0=24,
    210192146.0=25,
    1275118.0=26,
    4659656.0=27,
    209091416.0=28,
    209692891.0=29,
    107697436.0=30,
    209518228.0=31,
    211078002.0=32,
    209688652.0=33,
    209921231.0=34,
    209824867.0=35,
    209673949.0=36,
    209842048.0=37,
    8182823.0=38,
    209798865.0=39,
    1552384.0=40,
    209818962.0=41,
    209045727.0=42,
    209674270.0=43,
    209892725.0=44,
    58114564.0=45,
    208927896.0=46,
    210570269.0=47,
    209050993.0=48,
    209923303.0=49,
    210488058.0=50,
    208914286.0=51,
    210709803.0=52,
    210943575.0=53,
    209865519.0=54,
    209084673.0=55,
    210640426.0=56,
    70553579.0=57,
    208992025.0=58,
    209973945.0=59,
    209785341.0=60,
    209810063.0=61,
    209060715.0=62,
    209722457.0=63,
    209539924.0=64,
    209802609.0=65,
    210623843.0=66,
    210830766.0=67,
    209683152.0=68,
    209499354.0=69,
    210620987.0=70,
    209968540.0=71,
    209918443.0=72,
    209575028.0=73,
    210646799.0=74,
    210624714.0=75,
    209054310.0=76,
    209706044.0=77,
    209685472.0=78,
    210660376.0=79,
    114134551.0=80,
    209905405.0=81,
    209865237.0=82,
    209797492.0=83,
    210233819.0=84,
    210519382.0=85,
    209723629.0=86,
    209709679.0=87,
    210628279.0=88,
    210369097.0=89,
    209972181.0=90,
    9275272.0=91,
    209064416.0=92,
    110276377.0=93,
    209971737.0=94,
    32023895.0=95,
    209866894.0=96,
    140042478.0=97,
    209045711.0=98,
    209836059.0=99,
    209799189.0=100,
    209922231.0=101,
    210230813.0=102,
    209815595.0=103,
    54335231.0=104,
    209813841.0=105,
    210642702.0=106,
    209060600.0=107,
    209804657.0=108,
    209485498.0=109,
    209799194.0=110,
    209058193.0=111,
    208944877.0=112,
    25154813.0=113,
    209723672.0=114,
    211084916.0=115,
    209923003.0=116,
    2272609.0=117,
    209922935.0=118,
    209922929.0=119,
    209537361.0=120,
    43447701.0=121,
    208921748.0=122,
    209562939.0=123,
    210624700.0=124,
    209966110.0=125,
    210660956.0=126,
    209922528.0=127,
    208900651.0=128,
    211086885.0=129,
    208935742.0=130,
    209682872.0=131,
    208911970.0=132,
    118790722.0=133,
    209834452.0=134,
    209479787.0=135,
    23002760.0=136,
    209539892.0=137,
    209597151.0=138,
    208970579.0=139,
    209889755.0=140,
    210628188.0=141,
    210713464.0=142,
    1533983.0=143,
    211169275.0=144,
    209972877.0=145,
    209030336.0=146,
    209129597.0=147,
    209867187.0=148,
    211152178.0=149,
    209515365.0=150,
    209485038.0=151,
    209555134.0=152,
    209722184.0=153,
    209514218.0=154,
    209522524.0=155,
    87632830.0=156,
    209161715.0=157,
    209052413.0=158,
    209054636.0=159,
    209798859.0=160,
    209798851.0=161,
    209785327.0=162,
    209057696.0=163,
    210624703.0=164,
    190440214.0=165,
    209796911.0=166,
    209527608.0=167,
    211083061.0=168,
    2107102.0=169,
    209498993.0=170,
    53158431.0=171,
    209673899.0=172,
    94429635.0=173,
    208959966.0=174,
    209150797.0=175,
    209799187.0=176,
    209982244.0=177,
    209523687.0=178,
    209723687.0=179,
    209836829.0=180,
    211181064.0=181,
    209052730.0=182,
    209975318.0=183,
    209539876.0=184,
    209539728.0=185,
    209964071.0=186,
    209673948.0=187,
    209678295.0=188,
    209045719.0=189,
    209674266.0=190,
    209922538.0=191,
    209866533.0=192,
    209866360.0=193,
    210570551.0=194,
    209922222.0=195,
    209680209.0=196,
    210943583.0=197,
    209864872.0=198,
    210573258.0=199,
    209669184.0=200,
    209505350.0=201,
    209046118.0=202,
    209541751.0=203,
    209482814.0=204,
    209921572.0=205,
    209867496.0=206,
    209867494.0=207,
    210636318.0=208,
    209479777.0=209,
    210662684.0=210,
    163919062.0=211,
    209499242.0=212,
    209499240.0=213,
    209537525.0=214,
    55070629.0=215,
    209525408.0=216,
    25154839.0=217,
    25154862.0=218,
    104483720.0=219,
    209923327.0=220,
    210624706.0=221,
    209080442.0=222,
    209961356.0=223,
    210708869.0=224,
    209565381.0=225,
    209921515.0=226,
    54618280.0=227,
    209809733.0=228,
    208970977.0=229,
    210625257.0=230,
    210639090.0=231,
    209982240.0=232,
    210846805.0=233,
    209521902.0=234,
    51394168.0=235,
    209814125.0=236,
    209722177.0=237,
    209045705.0=238,
    210624713.0=239,
    209485480.0=240,
    43531652.0=241,
    209525755.0=242,
    209922530.0=243,
    209485040.0=244,
    209809720.0=245,
    209844295.0=246,
    22226403.0=247,
    208969679.0=248,
    211170015.0=249,
    51394132.0=250,
    209596325.0=251,
    209531144.0=252,
    209555593.0=253,
    209485137.0=254,
    209673883.0=255,
    209673652.0=256,
    209485057.0=257,
    209485610.0=258,
    209805172.0=259,
    210625509.0=260,
    209051931.0=261,
    209782043.0=262,
    209518121.0=263,
    8203186.0=264,
    209973678.0=265,
    209532554.0=266,
    208921478.0=267,
    209672239.0=268,
    209518125.0=269,
    209499458.0=270,
    209842056.0=271,
    209836334.0=272,
    209515363.0=273,
    209806741.0=274,
    208947780.0=275,
    209485044.0=276,
    208901445.0=277,
    40168070.0=278,
    209093960.0=279,
    209118496.0=280,
    209050020.0=281,
    208960717.0=282,
    209596327.0=283,
    209531348.0=284,
    210642506.0=285,
    210387347.0=286,
    209526041.0=287,
    209695001.0=288,
    209695805.0=289,
    210624712.0=290,
    210646674.0=291,
    210638486.0=292,
    209970528.0=293,
    209701336.0=294,
    209485497.0=295,
    209805537.0=296,
    209524165.0=297,
    209498992.0=298,
    210624696.0=299,
    209514213.0=300,
    209118257.0=301,
    209723625.0=302,
    209518732.0=303,
    211083408.0=304,
    50104984.0=305,
    209830521.0=306,
    208904532.0=307,
    209077871.0=308,
    209160064.0=309,
    210957067.0=310,
    210368118.0=311,
    209970510.0=312,
    210636338.0=313,
    210930666.0=314,
    209482592.0=315,
    210635499.0=316,
    209521884.0=317,
    209867201.0=318,
    209893004.0=319,
    209921551.0=320,
    209722453.0=321,
    208969173.0=322,
    209710576.0=323,
    209490127.0=324,
    209838463.0=325,
    210507246.0=326,
    209695412.0=327,
    209817923.0=328,
    209531334.0=329,
    209839480.0=330,
    209510541.0=331,
    95117503.0=332,
    209490129.0=333,
    115333920.0=334,
    210201894.0=335,
    209826714.0=336,
    208900640.0=337,
    209972888.0=338,
    209522339.0=339,
    210627653.0=340,
    3566826.0=341,
    209906191.0=342,
    209946183.0=343,
    8521092.0=344,
    209681283.0=345,
    209478840.0=346,
    109730813.0=347,
    210574441.0=348,
    210628292.0=349,
    14944210.0=350,
    209478843.0=351,
    211090711.0=352,
    211119485.0=353,
    209694846.0=354,
    208960226.0=355,
    210626820.0=356,
    52704100.0=357,
    211092116.0=358,
    209822485.0=359,
    209704313.0=360,
    209587871.0=361,
    209974893.0=362,
    209519073.0=363,
    208902769.0=364,
    209043823.0=365,
    209806124.0=366,
    209671004.0=367,
    209809064.0=368,
    211085325.0=369,
    209541479.0=370,
    83525154.0=371,
    121459474.0=372,
    209922529.0=373,
    143959970.0=374,
    209596331.0=375,
    209833927.0=376,
    209946505.0=377,
    20002498.0=378,
    209525931.0=379,
    209596738.0=380,
    77782188.0=381,
    210670745.0=382,
    208909714.0=383,
    210624882.0=384,
    211078006.0=385,
    209053064.0=386,
    209065141.0=387,
    209895646.0=388,
    209118635.0=389,
    209723662.0=390,
    209499380.0=391,
    209042752.0=392,
    209671389.0=393,
    209499638.0=394,
    209535127.0=395,
    53118222.0=396,
    209478837.0=397,
    209946514.0=398,
    209922228.0=399,
    209812911.0=400,
    209493623.0=401,
    209493620.0=402,
    83525157.0=403,
    83525156.0=404,
    208904726.0=405,
    209037145.0=406,
    138359626.0=407,
    209946527.0=408,
    209139836.0=409,
    210373225.0=410,
    209050851.0=411,
    208961542.0=412,
    210394281.0=413,
    211095800.0=414,
    209695451.0=415,
    9801858.0=416,
    58865613.0=417,
    150067970.0=418,
    209923005.0=419,
    58918333.0=420,
    210624701.0=421,
    209918748.0=422,
    209478839.0=423,
    209705074.0=424,
    58913964.0=425,
    209867499.0=426,
    209798862.0=427,
    209522313.0=428,
    209796394.0=429,
    209834203.0=430,
    208931358.0=431,
    210625512.0=432,
    210366116.0=433,
    209822487.0=434,
    209533785.0=435,
    209044304.0=436,
    209523197.0=437,
    51018142.0=438,
    30886080.0=439,
    210507234.0=440,
    210636771.0=441,
    209088168.0=442,
    209970537.0=443,
    209070934.0=444,
    209843368.0=445,
    209530380.0=446,
    209138562.0=447,
    209972861.0=448,
    208913476.0=449,
    120843705.0=450,
    209554638.0=451,
    209823054.0=452,
    209822489.0=453,
    209970545.0=454,
    209722170.0=455,
    209125712.0=456,
    209479724.0=457,
    27653479.0=458,
    209499243.0=459,
    209051209.0=460,
    209480688.0=461,
    77775952.0=462,
    210403106.0=463,
    3783350.0=464,
    209818218.0=465,
    209512730.0=466,
    210624884.0=467,
    208928467.0=468,
    209797619.0=469,
    209942282.0=470,
    209061548.0=471,
    209811752.0=472,
    209537369.0=473,
    209510523.0=474,
    209970515.0=475,
    209961366.0=476,
    210709810.0=477,
    209796391.0=478,
    211120424.0=479,
    26303286.0=480,
    209521882.0=481,
    209680771.0=482,
    209533786.0=483,
    51619871.0=484,
    209922541.0=485,
    210646327.0=486,
    209517884.0=487,
    209878477.0=488,
    209487354.0=489,
    209866556.0=490,
    209530780.0=491,
    209531124.0=492,
    209523824.0=493,
    210637584.0=494,
    210642271.0=495,
    209837589.0=496,
    209685497.0=497,
    209037166.0=498,
    208909658.0=499,
    210397358.0=500,
    209531037.0=501,
    208910380.0=502,
    211092325.0=503,
    209118261.0=504,
    210644771.0=505,
    33428696.0=506,
    209515367.0=507,
    209590611.0=508,
    209532564.0=509,
    209571418.0=510,
    211087780.0=511,
    209801054.0=512,
    22995113.0=513,
    210636309.0=514,
    209028819.0=515,
    209825447.0=516,
    208911102.0=517,
    209689418.0=518,
    208931411.0=519,
    209972906.0=520,
    208991798.0=521,
    25155718.0=522,
    209029156.0=523,
    209485035.0=524,
    208909650.0=525,
    209488132.0=526,
    209522039.0=527,
    209867207.0=528,
    209867206.0=529,
    46932930.0=530,
    209486126.0=531,
    210636396.0=532,
    209522297.0=533,
    209517742.0=534,
    209811519.0=535,
    209486818.0=536,
    209077867.0=537,
    209511361.0=538,
    209511358.0=539,
    209052468.0=540,
    209706038.0=541,
    58112623.0=542,
    209521972.0=543,
    208904961.0=544,
    209045471.0=545,
    209814467.0=546,
    210672250.0=547,
    210643790.0=548,
    209086584.0=549,
    209946889.0=550,
    209531708.0=551,
    209965106.0=552,
    209522042.0=553,
    209674268.0=554,
    209798844.0=555,
    211087789.0=556,
    209571107.0=557,
    209807092.0=558,
    209694819.0=559,
    209518754.0=560,
    140975824.0=561,
    209488424.0=562,
    209479773.0=563,
    210624705.0=564,
    208921741.0=565,
    209064129.0=566,
    209677633.0=567,
    209053077.0=568,
    209867501.0=569,
    208944591.0=570,
    208948658.0=571,
    210508856.0=572,
    208928076.0=573,
    209516184.0=574,
    211091078.0=575,
    209794828.0=576,
    209046121.0=577,
    210367157.0=578,
    210396663.0=579,
    209722450.0=580,
    850645.0=581,
    209482853.0=582,
    209682060.0=583,
    210640850.0=584,
    209970517.0=585,
    208993106.0=586,
    81834567.0=587,
    209067879.0=588,
    208997267.0=589,
    209065945.0=590,
    53329746.0=591,
    209701749.0=592,
    209485488.0=593,
    209485047.0=594,
    209681263.0=595,
    209805526.0=596,
    209798861.0=597,
    209680861.0=598,
    209682855.0=599,
    54268187.0=600,
    209701751.0=601,
    210233475.0=602,
    209045696.0=603,
    96382692.0=604,
    210975906.0=605,
    209866541.0=606,
    210642699.0=607,
    209709674.0=608,
    211119690.0=609,
    209796397.0=610,
    209722461.0=611,
    209515844.0=612,
    209879340.0=613,
    209796165.0=614,
    208925967.0=615,
    209483930.0=616,
    209522745.0=617,
    209030341.0=618,
    209517738.0=619,
    211083395.0=620,
    209723655.0=621,
    210628282.0=622,
    208963301.0=623,
    209577997.0=624,
    209682852.0=625,
    209922226.0=626,
    74075669.0=627,
    210652905.0=628,
    211088967.0=629,
    209052847.0=630,
    209512149.0=631,
    209521989.0=632,
    209051283.0=633,
    209921981.0=634,
    209596024.0=635,
    209541747.0=636,
    209979041.0=637,
    209499350.0=638,
    209480690.0=639,
    209093705.0=640,
    209555131.0=641,
    209522272.0=642,
    208959034.0=643,
    209970507.0=644,
    209561689.0=645,
    209522541.0=646,
    210643786.0=647,
    209522526.0=648,
    208967566.0=649,
    210943573.0=650,
    211083401.0=651,
    209031542.0=652,
    210365374.0=653,
    209499246.0=654,
    209062970.0=655,
    209669583.0=656,
    83525158.0=657,
    210278727.0=658,
    210640144.0=659,
    210646334.0=660,
    210412384.0=661,
    209979679.0=662,
    209683499.0=663,
    209068753.0=664,
    209522305.0=665,
    209681254.0=666,
    210627663.0=667,
    209751853.0=668,
    209727886.0=669,
    210643804.0=670,
    209053086.0=671,
    122707305.0=672,
    210635984.0=673,
    210635981.0=674,
    210206969.0=675,
    209526176.0=676,
    209685477.0=677,
    209521887.0=678,
    85694207.0=679,
    210389656.0=680,
    209527133.0=681,
    210366127.0=682,
    208931582.0=683,
    210320960.0=684,
    209539733.0=685,
    209522304.0=686,
    209063361.0=687,
    208917612.0=688,
    208969303.0=689,
    209525247.0=690,
    209050327.0=691,
    210871896.0=692,
    209681387.0=693,
    209539886.0=694,
    210638488.0=695,
    209061557.0=696,
    209063357.0=697,
    209682050.0=698,
    210380262.0=699,
    209682048.0=700,
    208992305.0=701,
    42834266.0=702,
    210638701.0=703,
    209522533.0=704,
    163784570.0=705,
    209691967.0=706,
    209866555.0=707,
    209053093.0=708,
    209485037.0=709,
    210368815.0=710,
    210370556.0=711,
    209568490.0=712,
    24051859.0=713,
    208948655.0=714,
    106087814.0=715,
    209051294.0=716,
    209695804.0=717,
    209677582.0=718,
    50942668.0=719,
    210370539.0=720,
    211083096.0=721,
    209798867.0=722,
    209923309.0=723,
    208948278.0=724,
    209531135.0=725,
    34570609.0=726,
    210645872.0=727,
    210232205.0=728,
    53285642.0=729,
    209803038.0=730,
    209679681.0=731,
    210638695.0=732,
    210248451.0=733,
    209674257.0=734,
    209971709.0=735,
    209503437.0=736,
    209482841.0=737,
    209522034.0=738,
    209842041.0=739,
    210628998.0=740,
    210232606.0=741,
    60114653.0=742,
    80279852.0=743,
    209522528.0=744,
    209052474.0=745,
    209140981.0=746,
    209962612.0=747,
    209729963.0=748,
    209809451.0=749,
    209839780.0=750,
    209825801.0=751,
    209947246.0=752,
    209971173.0=753,
    209075128.0=754,
    208969667.0=755,
    145056524.0=756,
    209805539.0=757,
    208931388.0=758,
    210664815.0=759,
    209525915.0=760,
    209695448.0=761,
    20030272.0=762,
    209683500.0=763,
    209844170.0=764,
    209681391.0=765,
    209756766.0=766,
    209526419.0=767,
    209922542.0=768,
    208948283.0=769,
    209126997.0=770,
    209905144.0=771,
    209531343.0=772,
    209030643.0=773,
    209949491.0=774,
    209051194.0=775,
    209054313.0=776,
    209918743.0=777,
    209722188.0=778,
    209515366.0=779,
    209945629.0=780,
    209945016.0=781,
    209704311.0=782,
    209526055.0=783,
    210638473.0=784,
    38494021.0=785,
    209050859.0=786,
    209890590.0=787,
    209052396.0=788,
    209043819.0=789,
    211088962.0=790,
    209561676.0=791,
    210635497.0=792,
    209040244.0=793,
    210508548.0=794,
    209069871.0=795,
    209923009.0=796,
    210643424.0=797,
    209971727.0=798,
    209809062.0=799,
    209704312.0=800,
    209722458.0=801,
    58918503.0=802,
    209084102.0=803,
    210403108.0=804,
    208947999.0=805,
    210655664.0=806,
    209050862.0=807,
    81827657.0=808,
    209971407.0=809,
    208930291.0=810,
    209730304.0=811,
    211088954.0=812,
    209482870.0=813,
    209825743.0=814,
    209970505.0=815,
    209922227.0=816,
    209922229.0=817,
    210636827.0=818,
    209059761.0=819,
    210368812.0=820,
    107364854.0=821,
    210944633.0=822,
    209054965.0=823,
    209922540.0=824,
    211090714.0=825,
    211089021.0=826,
    209125646.0=827,
    209924804.0=828,
    209687545.0=829,
    209685076.0=830,
    209950868.0=831,
    210639339.0=832,
    208930307.0=833,
    210510738.0=834,
    209141540.0=835,
    133212313.0=836,
    210642754.0=837,
    209807087.0=838,
    210380697.0=839,
    209753752.0=840,
    210239451.0=841,
    209524153.0=842,
    209044340.0=843,
    211184525.0=844,
    209894140.0=845,
    209838453.0=846,
    209701748.0=847,
    209961474.0=848,
    210657608.0=849,
    209064452.0=850,
    209680989.0=851,
    209531711.0=852,
    211101452.0=853,
    209972893.0=854,
    209803040.0=855,
    209970520.0=856,
    60102676.0=857,
    208931421.0=858,
    209922515.0=859,
    209678300.0=860,
    209923295.0=861,
    209521880.0=862,
    210628484.0=863,
    211087476.0=864,
    209067185.0=865,
    209045026.0=866,
    209946182.0=867,
    209522014.0=868,
    209828537.0=869,
    209678569.0=870,
    209888701.0=871,
    211089437.0=872,
    210448457.0=873,
    210405839.0=874,
    209527121.0=875,
    98922712.0=876,
    209071105.0=877,
    210642727.0=878,
    209825437.0=879,
    209490521.0=880,
    63472808.0=881,
    209084078.0=882,
    210368819.0=883,
    209509084.0=884,
    209124207.0=885,
    162721834.0=886,
    208969189.0=887,
    209539327.0=888,
    209949241.0=889,
    209922223.0=890,
    210636785.0=891,
    209039347.0=892,
    211085853.0=893,
    209921280.0=894,
    210506329.0=895,
    208952465.0=896,
    210368107.0=897,
    209946892.0=898,
    210710768.0=899,
  },
  reverse_mapping={
    0=209556175.0,
    1=52934000.0,
    2=37574467.0,
    3=209972191.0,
    4=73339227.0,
    5=209837677.0,
    6=5286455.0,
    7=209826974.0,
    8=210644361.0,
    9=25642291.0,
    10=209952987.0,
    11=209952974.0,
    12=211086336.0,
    13=209724105.0,
    14=209045031.0,
    15=210640906.0,
    16=209681259.0,
    17=209118488.0,
    18=209794811.0,
    19=209487402.0,
    20=209678521.0,
    21=209533787.0,
    22=209918381.0,
    23=209537331.0,
    24=209905828.0,
    25=210192146.0,
    26=1275118.0,
    27=4659656.0,
    28=209091416.0,
    29=209692891.0,
    30=107697436.0,
    31=209518228.0,
    32=211078002.0,
    33=209688652.0,
    34=209921231.0,
    35=209824867.0,
    36=209673949.0,
    37=209842048.0,
    38=8182823.0,
    39=209798865.0,
    40=1552384.0,
    41=209818962.0,
    42=209045727.0,
    43=209674270.0,
    44=209892725.0,
    45=58114564.0,
    46=208927896.0,
    47=210570269.0,
    48=209050993.0,
    49=209923303.0,
    50=210488058.0,
    51=208914286.0,
    52=210709803.0,
    53=210943575.0,
    54=209865519.0,
    55=209084673.0,
    56=210640426.0,
    57=70553579.0,
    58=208992025.0,
    59=209973945.0,

In [ ]:
print(pyg_graphs[20].timestep)

print(pyg_graphs[20].num_communities)

print(len(pyg_graphs[20].node_mapping))

20
327
900

GRAPHSAGE TESTING

In [ ]:
import importlib
import src.models.graphsage

importlib.reload(src.models.graphsage)

In [ ]:
from src.graph.converter import GraphConverter

pyg_graphs = GraphConverter.convert_all(
    pipeline.graphs
)

graphs = list(
    pyg_graphs.values()
)

In [ ]:
graphs[0]

Data(
  x=[900, 165],
  edge_index=[2, 1226],
  y=[900],
  community=[900],
  node_mapping={
    209556175.0=0,
    52934000.0=1,
    37574467.0=2,
    209972191.0=3,
    73339227.0=4,
    209837677.0=5,
    5286455.0=6,
    209826974.0=7,
    210644361.0=8,
    25642291.0=9,
    209952987.0=10,
    209952974.0=11,
    211086336.0=12,
    209724105.0=13,
    209045031.0=14,
    210640906.0=15,
    209681259.0=16,
    209118488.0=17,
    209794811.0=18,
    209487402.0=19,
    209678521.0=20,
    209533787.0=21,
    209918381.0=22,
    209537331.0=23,
    209905828.0=24,
    210192146.0=25,
    1275118.0=26,
    4659656.0=27,
    209091416.0=28,
    209692891.0=29,
    107697436.0=30,
    209518228.0=31,
    211078002.0=32,
    209688652.0=33,
    209921231.0=34,
    209824867.0=35,
    209673949.0=36,
    209842048.0=37,
    8182823.0=38,
    209798865.0=39,
    1552384.0=40,
    209818962.0=41,
    209045727.0=42,
    209674270.0=43,
    209892725.0=44,
    58114564.0=45,
    208927896.0=46,
    210570269.0=47,
    209050993.0=48,
    209923303.0=49,
    210488058.0=50,
    208914286.0=51,
    210709803.0=52,
    210943575.0=53,
    209865519.0=54,
    209084673.0=55,
    210640426.0=56,
    70553579.0=57,
    208992025.0=58,
    209973945.0=59,
    209785341.0=60,
    209810063.0=61,
    209060715.0=62,
    209722457.0=63,
    209539924.0=64,
    209802609.0=65,
    210623843.0=66,
    210830766.0=67,
    209683152.0=68,
    209499354.0=69,
    210620987.0=70,
    209968540.0=71,
    209918443.0=72,
    209575028.0=73,
    210646799.0=74,
    210624714.0=75,
    209054310.0=76,
    209706044.0=77,
    209685472.0=78,
    210660376.0=79,
    114134551.0=80,
    209905405.0=81,
    209865237.0=82,
    209797492.0=83,
    210233819.0=84,
    210519382.0=85,
    209723629.0=86,
    209709679.0=87,
    210628279.0=88,
    210369097.0=89,
    209972181.0=90,
    9275272.0=91,
    209064416.0=92,
    110276377.0=93,
    209971737.0=94,
    32023895.0=95,
    209866894.0=96,
    140042478.0=97,
    209045711.0=98,
    209836059.0=99,
    209799189.0=100,
    209922231.0=101,
    210230813.0=102,
    209815595.0=103,
    54335231.0=104,
    209813841.0=105,
    210642702.0=106,
    209060600.0=107,
    209804657.0=108,
    209485498.0=109,
    209799194.0=110,
    209058193.0=111,
    208944877.0=112,
    25154813.0=113,
    209723672.0=114,
    211084916.0=115,
    209923003.0=116,
    2272609.0=117,
    209922935.0=118,
    209922929.0=119,
    209537361.0=120,
    43447701.0=121,
    208921748.0=122,
    209562939.0=123,
    210624700.0=124,
    209966110.0=125,
    210660956.0=126,
    209922528.0=127,
    208900651.0=128,
    211086885.0=129,
    208935742.0=130,
    209682872.0=131,
    208911970.0=132,
    118790722.0=133,
    209834452.0=134,
    209479787.0=135,
    23002760.0=136,
    209539892.0=137,
    209597151.0=138,
    208970579.0=139,
    209889755.0=140,
    210628188.0=141,
    210713464.0=142,
    1533983.0=143,
    211169275.0=144,
    209972877.0=145,
    209030336.0=146,
    209129597.0=147,
    209867187.0=148,
    211152178.0=149,
    209515365.0=150,
    209485038.0=151,
    209555134.0=152,
    209722184.0=153,
    209514218.0=154,
    209522524.0=155,
    87632830.0=156,
    209161715.0=157,
    209052413.0=158,
    209054636.0=159,
    209798859.0=160,
    209798851.0=161,
    209785327.0=162,
    209057696.0=163,
    210624703.0=164,
    190440214.0=165,
    209796911.0=166,
    209527608.0=167,
    211083061.0=168,
    2107102.0=169,
    209498993.0=170,
    53158431.0=171,
    209673899.0=172,
    94429635.0=173,
    208959966.0=174,
    209150797.0=175,
    209799187.0=176,
    209982244.0=177,
    209523687.0=178,
    209723687.0=179,
    209836829.0=180,
    211181064.0=181,
    209052730.0=182,
    209975318.0=183,
    209539876.0=184,
    209539728.0=185,
    209964071.0=186,
    209673948.0=187,
    209678295.0=188,
    209045719.0=189,
    209674266.0=190,
    209922538.0=191,
    209866533.0=192,
    209866360.0=193,
    210570551.0=194,
    209922222.0=195,
    209680209.0=196,
    210943583.0=197,
    209864872.0=198,
    210573258.0=199,
    209669184.0=200,
    209505350.0=201,
    209046118.0=202,
    209541751.0=203,
    209482814.0=204,
    209921572.0=205,
    209867496.0=206,
    209867494.0=207,
    210636318.0=208,
    209479777.0=209,
    210662684.0=210,
    163919062.0=211,
    209499242.0=212,
    209499240.0=213,
    209537525.0=214,
    55070629.0=215,
    209525408.0=216,
    25154839.0=217,
    25154862.0=218,
    104483720.0=219,
    209923327.0=220,
    210624706.0=221,
    209080442.0=222,
    209961356.0=223,
    210708869.0=224,
    209565381.0=225,
    209921515.0=226,
    54618280.0=227,
    209809733.0=228,
    208970977.0=229,
    210625257.0=230,
    210639090.0=231,
    209982240.0=232,
    210846805.0=233,
    209521902.0=234,
    51394168.0=235,
    209814125.0=236,
    209722177.0=237,
    209045705.0=238,
    210624713.0=239,
    209485480.0=240,
    43531652.0=241,
    209525755.0=242,
    209922530.0=243,
    209485040.0=244,
    209809720.0=245,
    209844295.0=246,
    22226403.0=247,
    208969679.0=248,
    211170015.0=249,
    51394132.0=250,
    209596325.0=251,
    209531144.0=252,
    209555593.0=253,
    209485137.0=254,
    209673883.0=255,
    209673652.0=256,
    209485057.0=257,
    209485610.0=258,
    209805172.0=259,
    210625509.0=260,
    209051931.0=261,
    209782043.0=262,
    209518121.0=263,
    8203186.0=264,
    209973678.0=265,
    209532554.0=266,
    208921478.0=267,
    209672239.0=268,
    209518125.0=269,
    209499458.0=270,
    209842056.0=271,
    209836334.0=272,
    209515363.0=273,
    209806741.0=274,
    208947780.0=275,
    209485044.0=276,
    208901445.0=277,
    40168070.0=278,
    209093960.0=279,
    209118496.0=280,
    209050020.0=281,
    208960717.0=282,
    209596327.0=283,
    209531348.0=284,
    210642506.0=285,
    210387347.0=286,
    209526041.0=287,
    209695001.0=288,
    209695805.0=289,
    210624712.0=290,
    210646674.0=291,
    210638486.0=292,
    209970528.0=293,
    209701336.0=294,
    209485497.0=295,
    209805537.0=296,
    209524165.0=297,
    209498992.0=298,
    210624696.0=299,
    209514213.0=300,
    209118257.0=301,
    209723625.0=302,
    209518732.0=303,
    211083408.0=304,
    50104984.0=305,
    209830521.0=306,
    208904532.0=307,
    209077871.0=308,
    209160064.0=309,
    210957067.0=310,
    210368118.0=311,
    209970510.0=312,
    210636338.0=313,
    210930666.0=314,
    209482592.0=315,
    210635499.0=316,
    209521884.0=317,
    209867201.0=318,
    209893004.0=319,
    209921551.0=320,
    209722453.0=321,
    208969173.0=322,
    209710576.0=323,
    209490127.0=324,
    209838463.0=325,
    210507246.0=326,
    209695412.0=327,
    209817923.0=328,
    209531334.0=329,
    209839480.0=330,
    209510541.0=331,
    95117503.0=332,
    209490129.0=333,
    115333920.0=334,
    210201894.0=335,
    209826714.0=336,
    208900640.0=337,
    209972888.0=338,
    209522339.0=339,
    210627653.0=340,
    3566826.0=341,
    209906191.0=342,
    209946183.0=343,
    8521092.0=344,
    209681283.0=345,
    209478840.0=346,
    109730813.0=347,
    210574441.0=348,
    210628292.0=349,
    14944210.0=350,
    209478843.0=351,
    211090711.0=352,
    211119485.0=353,
    209694846.0=354,
    208960226.0=355,
    210626820.0=356,
    52704100.0=357,
    211092116.0=358,
    209822485.0=359,
    209704313.0=360,
    209587871.0=361,
    209974893.0=362,
    209519073.0=363,
    208902769.0=364,
    209043823.0=365,
    209806124.0=366,
    209671004.0=367,
    209809064.0=368,
    211085325.0=369,
    209541479.0=370,
    83525154.0=371,
    121459474.0=372,
    209922529.0=373,
    143959970.0=374,
    209596331.0=375,
    209833927.0=376,
    209946505.0=377,
    20002498.0=378,
    209525931.0=379,
    209596738.0=380,
    77782188.0=381,
    210670745.0=382,
    208909714.0=383,
    210624882.0=384,
    211078006.0=385,
    209053064.0=386,
    209065141.0=387,
    209895646.0=388,
    209118635.0=389,
    209723662.0=390,
    209499380.0=391,
    209042752.0=392,
    209671389.0=393,
    209499638.0=394,
    209535127.0=395,
    53118222.0=396,
    209478837.0=397,
    209946514.0=398,
    209922228.0=399,
    209812911.0=400,
    209493623.0=401,
    209493620.0=402,
    83525157.0=403,
    83525156.0=404,
    208904726.0=405,
    209037145.0=406,
    138359626.0=407,
    209946527.0=408,
    209139836.0=409,
    210373225.0=410,
    209050851.0=411,
    208961542.0=412,
    210394281.0=413,
    211095800.0=414,
    209695451.0=415,
    9801858.0=416,
    58865613.0=417,
    150067970.0=418,
    209923005.0=419,
    58918333.0=420,
    210624701.0=421,
    209918748.0=422,
    209478839.0=423,
    209705074.0=424,
    58913964.0=425,
    209867499.0=426,
    209798862.0=427,
    209522313.0=428,
    209796394.0=429,
    209834203.0=430,
    208931358.0=431,
    210625512.0=432,
    210366116.0=433,
    209822487.0=434,
    209533785.0=435,
    209044304.0=436,
    209523197.0=437,
    51018142.0=438,
    30886080.0=439,
    210507234.0=440,
    210636771.0=441,
    209088168.0=442,
    209970537.0=443,
    209070934.0=444,
    209843368.0=445,
    209530380.0=446,
    209138562.0=447,
    209972861.0=448,
    208913476.0=449,
    120843705.0=450,
    209554638.0=451,
    209823054.0=452,
    209822489.0=453,
    209970545.0=454,
    209722170.0=455,
    209125712.0=456,
    209479724.0=457,
    27653479.0=458,
    209499243.0=459,
    209051209.0=460,
    209480688.0=461,
    77775952.0=462,
    210403106.0=463,
    3783350.0=464,
    209818218.0=465,
    209512730.0=466,
    210624884.0=467,
    208928467.0=468,
    209797619.0=469,
    209942282.0=470,
    209061548.0=471,
    209811752.0=472,
    209537369.0=473,
    209510523.0=474,
    209970515.0=475,
    209961366.0=476,
    210709810.0=477,
    209796391.0=478,
    211120424.0=479,
    26303286.0=480,
    209521882.0=481,
    209680771.0=482,
    209533786.0=483,
    51619871.0=484,
    209922541.0=485,
    210646327.0=486,
    209517884.0=487,
    209878477.0=488,
    209487354.0=489,
    209866556.0=490,
    209530780.0=491,
    209531124.0=492,
    209523824.0=493,
    210637584.0=494,
    210642271.0=495,
    209837589.0=496,
    209685497.0=497,
    209037166.0=498,
    208909658.0=499,
    210397358.0=500,
    209531037.0=501,
    208910380.0=502,
    211092325.0=503,
    209118261.0=504,
    210644771.0=505,
    33428696.0=506,
    209515367.0=507,
    209590611.0=508,
    209532564.0=509,
    209571418.0=510,
    211087780.0=511,
    209801054.0=512,
    22995113.0=513,
    210636309.0=514,
    209028819.0=515,
    209825447.0=516,
    208911102.0=517,
    209689418.0=518,
    208931411.0=519,
    209972906.0=520,
    208991798.0=521,
    25155718.0=522,
    209029156.0=523,
    209485035.0=524,
    208909650.0=525,
    209488132.0=526,
    209522039.0=527,
    209867207.0=528,
    209867206.0=529,
    46932930.0=530,
    209486126.0=531,
    210636396.0=532,
    209522297.0=533,
    209517742.0=534,
    209811519.0=535,
    209486818.0=536,
    209077867.0=537,
    209511361.0=538,
    209511358.0=539,
    209052468.0=540,
    209706038.0=541,
    58112623.0=542,
    209521972.0=543,
    208904961.0=544,
    209045471.0=545,
    209814467.0=546,
    210672250.0=547,
    210643790.0=548,
    209086584.0=549,
    209946889.0=550,
    209531708.0=551,
    209965106.0=552,
    209522042.0=553,
    209674268.0=554,
    209798844.0=555,
    211087789.0=556,
    209571107.0=557,
    209807092.0=558,
    209694819.0=559,
    209518754.0=560,
    140975824.0=561,
    209488424.0=562,
    209479773.0=563,
    210624705.0=564,
    208921741.0=565,
    209064129.0=566,
    209677633.0=567,
    209053077.0=568,
    209867501.0=569,
    208944591.0=570,
    208948658.0=571,
    210508856.0=572,
    208928076.0=573,
    209516184.0=574,
    211091078.0=575,
    209794828.0=576,
    209046121.0=577,
    210367157.0=578,
    210396663.0=579,
    209722450.0=580,
    850645.0=581,
    209482853.0=582,
    209682060.0=583,
    210640850.0=584,
    209970517.0=585,
    208993106.0=586,
    81834567.0=587,
    209067879.0=588,
    208997267.0=589,
    209065945.0=590,
    53329746.0=591,
    209701749.0=592,
    209485488.0=593,
    209485047.0=594,
    209681263.0=595,
    209805526.0=596,
    209798861.0=597,
    209680861.0=598,
    209682855.0=599,
    54268187.0=600,
    209701751.0=601,
    210233475.0=602,
    209045696.0=603,
    96382692.0=604,
    210975906.0=605,
    209866541.0=606,
    210642699.0=607,
    209709674.0=608,
    211119690.0=609,
    209796397.0=610,
    209722461.0=611,
    209515844.0=612,
    209879340.0=613,
    209796165.0=614,
    208925967.0=615,
    209483930.0=616,
    209522745.0=617,
    209030341.0=618,
    209517738.0=619,
    211083395.0=620,
    209723655.0=621,
    210628282.0=622,
    208963301.0=623,
    209577997.0=624,
    209682852.0=625,
    209922226.0=626,
    74075669.0=627,
    210652905.0=628,
    211088967.0=629,
    209052847.0=630,
    209512149.0=631,
    209521989.0=632,
    209051283.0=633,
    209921981.0=634,
    209596024.0=635,
    209541747.0=636,
    209979041.0=637,
    209499350.0=638,
    209480690.0=639,
    209093705.0=640,
    209555131.0=641,
    209522272.0=642,
    208959034.0=643,
    209970507.0=644,
    209561689.0=645,
    209522541.0=646,
    210643786.0=647,
    209522526.0=648,
    208967566.0=649,
    210943573.0=650,
    211083401.0=651,
    209031542.0=652,
    210365374.0=653,
    209499246.0=654,
    209062970.0=655,
    209669583.0=656,
    83525158.0=657,
    210278727.0=658,
    210640144.0=659,
    210646334.0=660,
    210412384.0=661,
    209979679.0=662,
    209683499.0=663,
    209068753.0=664,
    209522305.0=665,
    209681254.0=666,
    210627663.0=667,
    209751853.0=668,
    209727886.0=669,
    210643804.0=670,
    209053086.0=671,
    122707305.0=672,
    210635984.0=673,
    210635981.0=674,
    210206969.0=675,
    209526176.0=676,
    209685477.0=677,
    209521887.0=678,
    85694207.0=679,
    210389656.0=680,
    209527133.0=681,
    210366127.0=682,
    208931582.0=683,
    210320960.0=684,
    209539733.0=685,
    209522304.0=686,
    209063361.0=687,
    208917612.0=688,
    208969303.0=689,
    209525247.0=690,
    209050327.0=691,
    210871896.0=692,
    209681387.0=693,
    209539886.0=694,
    210638488.0=695,
    209061557.0=696,
    209063357.0=697,
    209682050.0=698,
    210380262.0=699,
    209682048.0=700,
    208992305.0=701,
    42834266.0=702,
    210638701.0=703,
    209522533.0=704,
    163784570.0=705,
    209691967.0=706,
    209866555.0=707,
    209053093.0=708,
    209485037.0=709,
    210368815.0=710,
    210370556.0=711,
    209568490.0=712,
    24051859.0=713,
    208948655.0=714,
    106087814.0=715,
    209051294.0=716,
    209695804.0=717,
    209677582.0=718,
    50942668.0=719,
    210370539.0=720,
    211083096.0=721,
    209798867.0=722,
    209923309.0=723,
    208948278.0=724,
    209531135.0=725,
    34570609.0=726,
    210645872.0=727,
    210232205.0=728,
    53285642.0=729,
    209803038.0=730,
    209679681.0=731,
    210638695.0=732,
    210248451.0=733,
    209674257.0=734,
    209971709.0=735,
    209503437.0=736,
    209482841.0=737,
    209522034.0=738,
    209842041.0=739,
    210628998.0=740,
    210232606.0=741,
    60114653.0=742,
    80279852.0=743,
    209522528.0=744,
    209052474.0=745,
    209140981.0=746,
    209962612.0=747,
    209729963.0=748,
    209809451.0=749,
    209839780.0=750,
    209825801.0=751,
    209947246.0=752,
    209971173.0=753,
    209075128.0=754,
    208969667.0=755,
    145056524.0=756,
    209805539.0=757,
    208931388.0=758,
    210664815.0=759,
    209525915.0=760,
    209695448.0=761,
    20030272.0=762,
    209683500.0=763,
    209844170.0=764,
    209681391.0=765,
    209756766.0=766,
    209526419.0=767,
    209922542.0=768,
    208948283.0=769,
    209126997.0=770,
    209905144.0=771,
    209531343.0=772,
    209030643.0=773,
    209949491.0=774,
    209051194.0=775,
    209054313.0=776,
    209918743.0=777,
    209722188.0=778,
    209515366.0=779,
    209945629.0=780,
    209945016.0=781,
    209704311.0=782,
    209526055.0=783,
    210638473.0=784,
    38494021.0=785,
    209050859.0=786,
    209890590.0=787,
    209052396.0=788,
    209043819.0=789,
    211088962.0=790,
    209561676.0=791,
    210635497.0=792,
    209040244.0=793,
    210508548.0=794,
    209069871.0=795,
    209923009.0=796,
    210643424.0=797,
    209971727.0=798,
    209809062.0=799,
    209704312.0=800,
    209722458.0=801,
    58918503.0=802,
    209084102.0=803,
    210403108.0=804,
    208947999.0=805,
    210655664.0=806,
    209050862.0=807,
    81827657.0=808,
    209971407.0=809,
    208930291.0=810,
    209730304.0=811,
    211088954.0=812,
    209482870.0=813,
    209825743.0=814,
    209970505.0=815,
    209922227.0=816,
    209922229.0=817,
    210636827.0=818,
    209059761.0=819,
    210368812.0=820,
    107364854.0=821,
    210944633.0=822,
    209054965.0=823,
    209922540.0=824,
    211090714.0=825,
    211089021.0=826,
    209125646.0=827,
    209924804.0=828,
    209687545.0=829,
    209685076.0=830,
    209950868.0=831,
    210639339.0=832,
    208930307.0=833,
    210510738.0=834,
    209141540.0=835,
    133212313.0=836,
    210642754.0=837,
    209807087.0=838,
    210380697.0=839,
    209753752.0=840,
    210239451.0=841,
    209524153.0=842,
    209044340.0=843,
    211184525.0=844,
    209894140.0=845,
    209838453.0=846,
    209701748.0=847,
    209961474.0=848,
    210657608.0=849,
    209064452.0=850,
    209680989.0=851,
    209531711.0=852,
    211101452.0=853,
    209972893.0=854,
    209803040.0=855,
    209970520.0=856,
    60102676.0=857,
    208931421.0=858,
    209922515.0=859,
    209678300.0=860,
    209923295.0=861,
    209521880.0=862,
    210628484.0=863,
    211087476.0=864,
    209067185.0=865,
    209045026.0=866,
    209946182.0=867,
    209522014.0=868,
    209828537.0=869,
    209678569.0=870,
    209888701.0=871,
    211089437.0=872,
    210448457.0=873,
    210405839.0=874,
    209527121.0=875,
    98922712.0=876,
    209071105.0=877,
    210642727.0=878,
    209825437.0=879,
    209490521.0=880,
    63472808.0=881,
    209084078.0=882,
    210368819.0=883,
    209509084.0=884,
    209124207.0=885,
    162721834.0=886,
    208969189.0=887,
    209539327.0=888,
    209949241.0=889,
    209922223.0=890,
    210636785.0=891,
    209039347.0=892,
    211085853.0=893,
    209921280.0=894,
    210506329.0=895,
    208952465.0=896,
    210368107.0=897,
    209946892.0=898,
    210710768.0=899,
  },
  reverse_mapping={
    0=209556175.0,
    1=52934000.0,
    2=37574467.0,
    3=209972191.0,
    4=73339227.0,
    5=209837677.0,
    6=5286455.0,
    7=209826974.0,
    8=210644361.0,
    9=25642291.0,
    10=209952987.0,
    11=209952974.0,
    12=211086336.0,
    13=209724105.0,
    14=209045031.0,
    15=210640906.0,
    16=209681259.0,
    17=209118488.0,
    18=209794811.0,
    19=209487402.0,
    20=209678521.0,
    21=209533787.0,
    22=209918381.0,
    23=209537331.0,
    24=209905828.0,
    25=210192146.0,
    26=1275118.0,
    27=4659656.0,
    28=209091416.0,
    29=209692891.0,
    30=107697436.0,
    31=209518228.0,
    32=211078002.0,
    33=209688652.0,
    34=209921231.0,
    35=209824867.0,
    36=209673949.0,
    37=209842048.0,
    38=8182823.0,
    39=209798865.0,
    40=1552384.0,
    41=209818962.0,
    42=209045727.0,
    43=209674270.0,
    44=209892725.0,
    45=58114564.0,
    46=208927896.0,
    47=210570269.0,
    48=209050993.0,
    49=209923303.0,
    50=210488058.0,
    51=208914286.0,
    52=210709803.0,
    53=210943575.0,
    54=209865519.0,
    55=209084673.0,
    56=210640426.0,
    57=70553579.0,
    58=208992025.0,
    59=209973945.0,

In [ ]:
from importlib import reload
import src.models.graphsage

reload(src.models.graphsage)

from src.models.graphsage import GraphSAGEModel

In [ ]:
from src.graph.converter import GraphConverter

pyg_graphs = GraphConverter.convert_all(
    pipeline.graphs
)

graphs = list(
    pyg_graphs.values()
)

In [ ]:
sage = GraphSAGEModel(

    input_dim=graphs[0].num_node_features,

)

In [ ]:
import time
from types import MethodType

def debug_fit(self, graphs, epochs=5, verbose=True):

    if not isinstance(graphs, (list, tuple)):
        graphs = [graphs]

    self.model.train()

    history = []

    total_graphs = len(graphs)

    overall_start = time.time()

    print("=" * 60)
    print(f"Training on {total_graphs} graph(s)")
    print(f"Epochs: {epochs}")
    print("=" * 60)

    for epoch in range(epochs):

        epoch_start = time.time()

        epoch_loss = 0.0

        print(f"\nEpoch {epoch+1}/{epochs}")

        for graph_idx, data in enumerate(graphs):

            graph_start = time.time()

            self.optimizer.zero_grad()

            logits = self.forward(data)

            loss = self.loss_fn(
                logits,
                data.y,
            )

            loss.backward()

            self.optimizer.step()

            epoch_loss += loss.item()

            print(
                f"  Graph {graph_idx+1}/{total_graphs} | "
                f"Nodes={data.num_nodes:,} | "
                f"Edges={data.edge_index.shape[1]:,} | "
                f"Loss={loss.item():.4f} | "
                f"{time.time()-graph_start:.2f}s"
            )

        epoch_loss /= total_graphs

        history.append(epoch_loss)

        print(
            f"Epoch finished in "
            f"{time.time()-epoch_start:.2f}s | "
            f"Average Loss={epoch_loss:.4f}"
        )

    print("\nTraining Complete!")
    print(f"Total Time: {time.time()-overall_start:.2f}s")

    return history

# Replace only this instance's fit method
sage.fit = MethodType(debug_fit, sage)

In [ ]:
%whos

Variable                 Type                   Data/Info
---------------------------------------------------------
BaseModel                ABCMeta                <class 'src.models.base.BaseModel'>
EvaluationMetrics        type                   <class 'src.evaluation.me<...>trics.EvaluationMetrics'>
EvaluationReport         type                   <class 'src.evaluation.report.EvaluationReport'>
EvoFinGraphPipeline      type                   <class 'src.pipeline.buil<...>der.EvoFinGraphPipeline'>
GraphConverter           type                   <class 'src.graph.converter.GraphConverter'>
GraphSAGEModel           ABCMeta                <class 'src.models.graphsage.GraphSAGEModel'>
LogisticModel            ABCMeta                <class 'src.models.logistic.LogisticModel'>
MethodType               type                   <class 'method'>
ModelData                type                   <class 'src.models.data.ModelData'>
PROJECT_ROOT             PosixPath              /Users/apple/dev/EvoFinGraph
Path                     type                   <class 'pathlib._local.Path'>
XGBoostModel             ABCMeta                <class 'src.models.xgboost.XGBoostModel'>
X_test                   DataFrame              Shape: (106, 9)
X_train                  DataFrame              Shape: (422, 9)
comparison               DataFrame              Shape: (9, 2)
data                     Data                   Data(\n  x=[900, 165],\n <...>n  num_communities=327\n)
debug_fit                function               <function debug_fit at 0x11e56ce00>
feature_matrix           DataFrame              Shape: (528, 16)
graph                    DiGraph                DiGraph with 900 nodes and 613 edges
graphs                   list                   n=5
importance               dict                   n=9
importlib                module                 <module 'importlib' from <...>3/importlib/__init__.py'>
logistic_metrics         dict                   n=5
logistic_predictions     ndarray                106: 106 elems, type `int64`, 848 bytes
logistic_probabilities   ndarray                106: 106 elems, type `float64`, 848 bytes
metrics                  dict                   n=5
model                    LogisticModel          <src.models.logistic.Logi<...>el object at 0x11dff1be0>
np                       module                 <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                       module                 <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pipeline                 EvoFinGraphPipeline    <src.pipeline.builder.Evo<...>ne object at 0x11d032120>
predictions              ndarray                106: 106 elems, type `int64`, 848 bytes
probabilities            ndarray                106: 106 elems, type `float64`, 848 bytes
pyg_graphs               dict                   n=5
reload                   function               <function reload at 0x1059b7e20>
report                   EvaluationReport       <src.evaluation.report.Ev<...>rt object at 0x11d0f5d10>
sage                     GraphSAGEModel         <src.models.graphsage.Gra<...>el object at 0x11dff3380>
sklearn                  module                 <module 'sklearn' from '/<...>ges/sklearn/__init__.py'>
src                      module                 <module 'src' (namespace)<...>le/dev/EvoFinGraph/src']>
sys                      module                 <module 'sys' (built-in)>
time                     module                 <module 'time' (built-in)>
torch                    module                 <module 'torch' from '/Us<...>kages/torch/__init__.py'>
xgb                      XGBoostModel           <src.models.xgboost.XGBoo<...>el object at 0x11dff2a50>
xgb_metrics              dict                   n=5
xgb_predictions          ndarray                106: 106 elems, type `int64`, 848 bytes
xgb_probabilities        ndarray                106: 106 elems, type `float32`, 424 bytes
xgboost                  module                 <module 'xgboost' from '/<...>ges/xgboost/__init__.py'>
y_test                   Series                 Shape: (106,)
y_train                  Series                 Shape: (422,)

In [ ]:
print(len(graphs))

5

In [ ]:
for i, graph in enumerate(graphs):

    print(
        i,
        graph.num_nodes,
        graph.edge_index.shape[1],
    )

0 900 1226
1 641 1036
2 1763 3074
3 1187 2092
4 1126 1922

In [ ]:
sage = GraphSAGEModel(

    input_dim=graphs[0].num_node_features,

    hidden_dim=32,   # much faster for now

)

In [ ]:
history = sage.fit(
    graphs[-3:],
    epochs=5,
)

In [ ]:
predictions = sage.predict(
    graphs[-1]
)

probabilities = sage.predict_proba(
    graphs[-1]
)

In [ ]:
from src.evaluation.metrics import EvaluationMetrics

graphsage_metrics = EvaluationMetrics.compute(

    graphs[-1].y.numpy(),

    predictions,

    probabilities[:, 1],

)

graphsage_metrics

{'accuracy': 0.8490230905861457,
 'precision': 0.2676056338028169,
 'recall': 0.1386861313868613,
 'f1': 0.18269230769230768,
 'roc_auc': 0.7556847955244921}

SAGE EVALUATION

In [ ]:
predictions = sage.predict(
    graphs[-1]
)

probabilities = sage.predict_proba(
    graphs[-1]
)

In [ ]:
from src.evaluation.metrics import EvaluationMetrics

graphsage_metrics = EvaluationMetrics.compute(

    graphs[-1].y.numpy(),

    predictions,

    probabilities[:, 1],

)

graphsage_metrics

{'accuracy': 0.8490230905861457,
 'precision': 0.2676056338028169,
 'recall': 0.1386861313868613,
 'f1': 0.18269230769230768,
 'roc_auc': 0.7556847955244921}

In [ ]:
embeddings = sage.embeddings(
    graphs[-1]
)

embeddings.shape

(1126, 32)